module.exports = {
  meta: {
    page: 1,
    pageSize: 3,
    totalCount: 56,
  },
  filters: [],
  data: [
    {
      city: 'Oakton',
      country: 'United States',
      currentJobTitle: 'Senior Business & QA Analyst, Contract Project Manager for DHS USCIS',
      currentCompany: 'MaxiSoft Corp',
      education: [
        {
          degree: 'Masters',
          location: 'Odessa Ukraine',
          org: 'Odessa National Academy of Telecommunications',
        },
        {
          degree: 'Vocational School',
          location: 'Washington DC United States',
          org: 'GWU Business School',
        },
      ],
      experience: {
        current: {
          org: 'MaxiSoft Corp',
          periodEnd: {
            day: 1,
            month: 5,
            year: 2019,
          },
          periodStart: {
            day: 1,
            month: 9,
            year: 2017,
          },
          title: 'Senior Business & QA Analyst, Contract Project Manager for DHS USCIS',
        },
        history: [
          {
            org: 'MaxiSoft Corp',
            periodEnd: {
              day: 1,
              month: 5,
              year: 2019,
            },
            periodStart: {
              day: 1,
              month: 9,
              year: 2017,
            },
            title: 'Senior Business & QA Analyst, Contract Project Manager for DHS USCIS',
          },
          {
            org: 'Clarus Group, Accenture Federal Services',
            periodEnd: {
              day: 1,
              month: 10,
              year: 2019,
            },
            periodStart: {
              day: 1,
              month: 5,
              year: 2019,
            },
            title: 'Business Systems Analyst, QA Analyst for USPS',
          },
          {
            location: 'Lewes DE United States',
            org: 'Optimeet , Inc',
            periodEnd: {
              day: 1,
              month: 9,
              year: 2017,
            },
            periodStart: {
              day: 1,
              month: 3,
              year: 2014,
            },
            title: 'Senior Business Analyst, Product Manager',
          },
          {
            location: 'Oakton VA United States',
            org: 'Artex Consulting Inc',
            periodEnd: {
              day: 1,
              month: 2,
              year: 2014,
            },
            periodStart: {
              day: 1,
              month: 7,
              year: 2011,
            },
            title: 'Consultant',
          },
          {
            org: 'MacrosysRT, Inc',
            periodEnd: {
              day: 1,
              month: 4,
              year: 2011,
            },
            periodStart: {
              day: 1,
              month: 10,
              year: 2008,
            },
            title: 'Senior Airline Business Analyst / Head of Analytical Group for DOT BTS OAI',
          },
          {
            org: 'TetraTech, Inc',
            periodEnd: {
              day: 1,
              month: 10,
              year: 2008,
            },
            periodStart: {
              day: 1,
              month: 12,
              year: 2007,
            },
            title: 'Sr. System Analyst for DOT BTS OAI',
          },
          {
            location: 'Arlington VA United States',
            org: 'Avianation.com',
            periodEnd: {
              day: 1,
              month: 11,
              year: 2007,
            },
            periodStart: {
              day: 1,
              month: 10,
              year: 2006,
            },
            title: 'Contractor',
          },
          {
            location: 'Stuttgart Germany',
            org: 'Shape Services Inc',
            periodEnd: {
              day: 1,
              month: 11,
              year: 2006,
            },
            periodStart: {
              day: 1,
              month: 10,
              year: 2004,
            },
            title: 'Contractor',
          },
          {
            location: 'Bethesda MD United States',
            org: 'TDEC TECH',
            periodEnd: {
              day: 1,
              month: 4,
              year: 2004,
            },
            periodStart: {
              day: 1,
              month: 2,
              year: 2004,
            },
            title: 'Information Specialist, Manager',
          },
          {
            location: 'Atlanta GA United States',
            org: 'UPS, UPS Mail Innovations',
            periodEnd: {
              day: 1,
              month: 1,
              year: 2004,
            },
            periodStart: {
              day: 1,
              month: 1,
              year: 1999,
            },
            title: 'IT Manager',
          },
          {
            location: 'VA United States',
            org: 'Northern Virginia Community College',
            periodEnd: {
              day: 1,
              month: 3,
              year: 1999,
            },
            periodStart: {
              day: 1,
              month: 8,
              year: 1997,
            },
            title: 'Academic Computer Lab Instructor / Assistant',
          },
          {
            location: 'Odessa Ukraine',
            org: 'National Academy of Telecommunications',
            periodEnd: {
              day: 1,
              month: 1,
              year: 1990,
            },
            periodStart: {
              day: 1,
              month: 5,
              year: 1986,
            },
            title: 'Research Engineer',
          },
          {
            org: 'Contractor on behalf of Raventek Solutions, VA and Booz Allen Hamilton, VA',
            periodStart: {
              day: 1,
              month: 2,
              year: 2020,
            },
            title: 'Senior Business Systems Analyst, Engineer for VA',
          },
        ],
      },
      firstName: 'Sergey',
      fullName: 'Sergey Chuklin',
      dateLastActive: '2020-07-02T13:47:39Z',
      dateResumeLastUpdated: '2020-07-01T19:02:05Z',
      desiredJobTitles: ['Senior Business & QA Analyst, IT Manager'],
      hasEmail: true,
      hasPhone: true,
      id: 'de32af67b76c108cdb1b5dce1d3c7c1d57504108',
      legacyIds: [],
      imageUrl: 'https://cdn-assets.workdigital.co.uk/de32af67b76c108cdb1b5dce1d3c7c1d57504108',
      isThirdParty: false,
      lastName: 'Chuklin',
      likelyToMove: true,
      likelyToMoveScore: 100.0,
      locations: [
        {
          city: 'Oakton',
          country: 'United States',
          countryCode: 'US',
          latitude: 38.89235,
          longitude: -77.3267,
          region: 'Virginia',
          source: 'dice',
          text: 'Oakton, Virginia US',
        },
      ],
      region: 'Virginia',
      skills: [
        {
          lastUsed: 2020,
          skill: 'software',
          yearsUsed: 31,
        },
        {
          lastUsed: 2020,
          score: 15.0,
          skill: 'engineering',
          yearsUsed: 29,
        },
        {
          lastUsed: 2020,
          score: 15.0,
          skill: 'compliance',
          yearsUsed: 21,
        },
        {
          lastUsed: 2020,
          score: 15.0,
          skill: 'operations',
          yearsUsed: 21,
        },
        {
          lastUsed: 2020,
          score: 15.0,
          skill: 'change control',
          yearsUsed: 19,
        },
        {
          lastUsed: 2020,
          score: 15.0,
          skill: 'cyber security',
          yearsUsed: 19,
        },
        {
          lastUsed: 2020,
          score: 15.0,
          skill: 'ehr',
          yearsUsed: 19,
        },
        {
          lastUsed: 2020,
          score: 15.0,
          skill: 'network security',
          yearsUsed: 19,
        },
        {
          lastUsed: 2020,
          score: 15.0,
          skill: 'software deployment',
          yearsUsed: 19,
        },
        {
          lastUsed: 2020,
          skill: 'customer care and billing',
          yearsUsed: 19,
        },
        {
          lastUsed: 2020,
          skill: 'firewall',
          yearsUsed: 19,
        },
        {
          lastUsed: 2020,
          skill: 'metrics',
          yearsUsed: 19,
        },
        {
          lastUsed: 2019,
          score: 15.0,
          skill: 'qa',
          yearsUsed: 18,
        },
        {
          lastUsed: 2019,
          score: 15.0,
          skill: 'business requirements',
          yearsUsed: 14,
        },
        {
          lastUsed: 2019,
          score: 15.0,
          skill: 'consulting',
          yearsUsed: 13,
        },
        {
          lastUsed: 2019,
          score: 15.0,
          skill: 'reporting',
          yearsUsed: 10,
        },
        {
          lastUsed: 2019,
          skill: 'data transformation services',
          yearsUsed: 10,
        },
        {
          lastUsed: 2019,
          score: 15.0,
          skill: 'it management',
          yearsUsed: 8,
        },
        {
          lastUsed: 2019,
          score: 15.0,
          skill: 'project management',
          yearsUsed: 7,
        },
        {
          lastUsed: 2019,
          score: 15.0,
          skill: 'training',
          yearsUsed: 7,
        },
        {
          lastUsed: 2019,
          score: 15.0,
          skill: 'agile',
          yearsUsed: 6,
        },
        {
          lastUsed: 2017,
          skill: 'implementation',
          yearsUsed: 10,
        },
        {
          lastUsed: 2017,
          score: 15.0,
          skill: 'workflow',
          yearsUsed: 9,
        },
        {
          lastUsed: 2017,
          skill: 'controls',
          yearsUsed: 8,
        },
        {
          lastUsed: 2017,
          score: 15.0,
          skill: 'documentation',
          yearsUsed: 7,
        },
        {
          lastUsed: 2017,
          skill: 'database and sql',
          yearsUsed: 7,
        },
        {
          lastUsed: 2017,
          skill: 'real-time',
          yearsUsed: 7,
        },
        {
          lastUsed: 2017,
          score: 15.0,
          skill: 'business analysis',
          yearsUsed: 6,
        },
        {
          lastUsed: 2017,
          skill: 'senior management',
          yearsUsed: 2,
        },
        {
          lastUsed: 2015,
          score: 15.0,
          skill: 'infrastructure',
          yearsUsed: 3,
        },
        {
          lastUsed: 2014,
          skill: 'transportation',
          yearsUsed: 10,
        },
        {
          lastUsed: 2014,
          score: 15.0,
          skill: 'business process',
          yearsUsed: 9,
        },
        {
          lastUsed: 2014,
          skill: 'cost-benefit analysis',
          yearsUsed: 9,
        },
        {
          lastUsed: 2014,
          skill: 'presentations',
          yearsUsed: 7,
        },
        {
          lastUsed: 2014,
          score: 30.0,
          skill: 'sql',
          yearsUsed: 5,
        },
        {
          lastUsed: 2006,
          score: 15.0,
          skill: 'research',
          yearsUsed: 6,
        },
        {
          lastUsed: 2004,
          score: 15.0,
          skill: 'perl',
          yearsUsed: 6,
        },
        {
          lastUsed: 2004,
          score: 15.0,
          skill: 'security',
          yearsUsed: 6,
        },
        {
          skill: 'network',
          yearsUsed: 5,
        },
        {
          score: 15.0,
          skill: 'analysis',
        },
        {
          score: 15.0,
          skill: 'billing',
        },
        {
          score: 15.0,
          skill: 'customer care',
        },
        {
          score: 15.0,
          skill: 'data transformation',
        },
        {
          score: 15.0,
          skill: 'database',
        },
        {
          score: 15.0,
          skill: 'management',
        },
        {
          score: 15.0,
          skill: 'transportation engineering',
        },
      ],
      socialProfiles: [
        {
          icon_64: 'https://cdn-assets.workdigital.co.uk/icon/social/64/dice.png',
          source: 'Dice',
        },
      ],
      workPermitDocuments: ['US Citizenship'],
      workPermitLocations: ['US'],
      workPreferences: [
        {
          employmentType: ['Contract - W2', 'Contract to Hire - Independent', 'Full-time', 'Contract to Hire - W2', 'Contract - Independent'],
          hourlyRate: {
            currency: 'USD',
            max: 0,
            min: 62,
          },
          willingToRelocate: false,
          travelPreference: 25,
        },
        {
          employmentType: ['Contract - W2', 'Contract to Hire - Independent', 'Full-time', 'Contract to Hire - W2', 'Contract - Independent'],
          annualSalary: {
            currency: 'USD',
            max: 0,
            min: 110000,
          },
          willingToRelocate: false,
          travelPreference: 25,
        },
      ],
      yearsOfExperience: 34,
      securityAllowance: {
        status: false,
      },
      languages: [],
      citizenship: ['US'],
    },
    {
      city: 'Severn',
      country: 'United States',
      currentJobTitle: 'IT SUPPORT SUPERVISOR',
      currentCompany: 'STEPTOE & JOHNSON, LLP',
      education: [
        {
          degree: 'Bachelors',
          org: 'AMERICAN INTERCONTINENTAL UNIVERSITY',
        },
      ],
      experience: {
        current: {
          org: 'STEPTOE & JOHNSON, LLP',
          periodEnd: {
            day: 1,
            month: 2,
            year: 2020,
          },
          periodStart: {
            day: 1,
            month: 2,
            year: 2019,
          },
          title: 'IT SUPPORT SUPERVISOR',
        },
        history: [
          {
            org: 'STEPTOE & JOHNSON, LLP',
            periodEnd: {
              day: 1,
              month: 2,
              year: 2020,
            },
            periodStart: {
              day: 1,
              month: 2,
              year: 2019,
            },
            title: 'IT SUPPORT SUPERVISOR',
          },
          {
            org: 'BUCKLEY SANDLER, LLP',
            periodEnd: {
              day: 1,
              month: 2,
              year: 2019,
            },
            periodStart: {
              day: 1,
              month: 6,
              year: 2016,
            },
            title: 'SYSTEMS ADMINISTRATOR',
          },
          {
            org: 'BUCKLEY SANDLER, LLP',
            periodEnd: {
              day: 1,
              month: 6,
              year: 2016,
            },
            periodStart: {
              day: 1,
              month: 4,
              year: 2013,
            },
            title: 'HELP DESK SUPERVISOR',
          },
          {
            location: 'Gaithersburg MD United States',
            org: 'OPTIMAL NETWORKS, INC',
            periodEnd: {
              day: 1,
              month: 2,
              year: 2013,
            },
            periodStart: {
              day: 1,
              month: 4,
              year: 2005,
            },
            title: 'SENIOR NETWORK ENGINEER/CONSULTANT',
          },
          {
            location: 'Elkridge MD United States',
            org: 'PRIME OFFICE PRODUCTS',
            periodEnd: {
              day: 1,
              month: 3,
              year: 2005,
            },
            periodStart: {
              day: 1,
              month: 7,
              year: 2001,
            },
            title: 'REGIONAL DIRECTOR OF INFORMATION TECHNOLOGY',
          },
        ],
      },
      firstName: 'Ronald',
      fullName: 'Ronald Davis',
      dateLastActive: '2020-07-02T07:00:55Z',
      dateResumeLastUpdated: '2020-07-02T16:57:52Z',
      desiredJobTitles: ['IT SUPPORT SUPERVISOR'],
      hasEmail: true,
      hasPhone: true,
      id: 'de32af67b76c108cdb1b5dce1d3c7c1d57504108',
      legacyIds: [],
      isThirdParty: false,
      lastName: 'Davis',
      likelyToMove: true,
      likelyToMoveScore: 100.0,
      locations: [
        {
          city: 'Severn',
          country: 'United States',
          countryCode: 'US',
          latitude: 39.12142,
          longitude: -76.67592,
          region: 'Maryland',
          source: 'dice',
          text: 'Severn, Maryland US',
        },
      ],
      region: 'Maryland',
      skills: [
        {
          lastUsed: 2020,
          score: 15.0,
          skill: 'active directory',
          yearsUsed: 15,
        },
        {
          lastUsed: 2020,
          score: 15.0,
          skill: 'microsoft windows',
          yearsUsed: 15,
        },
        {
          lastUsed: 2020,
          score: 15.0,
          skill: 'technical support',
          yearsUsed: 15,
        },
        {
          lastUsed: 2020,
          score: 15.0,
          skill: 'it management',
          yearsUsed: 7,
        },
        {
          lastUsed: 2019,
          skill: 'procedure',
          yearsUsed: 14,
        },
        {
          lastUsed: 2019,
          score: 15.0,
          skill: 'project management',
          yearsUsed: 11,
        },
        {
          lastUsed: 2019,
          skill: 'installation',
          yearsUsed: 11,
        },
        {
          lastUsed: 2019,
          skill: 'upgrades',
          yearsUsed: 11,
        },
        {
          lastUsed: 2019,
          score: 15.0,
          skill: 'training',
          yearsUsed: 7,
        },
        {
          lastUsed: 2019,
          score: 15.0,
          skill: 'operations',
          yearsUsed: 6,
        },
        {
          lastUsed: 2019,
          score: 15.0,
          skill: 'customer service',
          yearsUsed: 4,
        },
        {
          lastUsed: 2019,
          score: 15.0,
          skill: 'service desk',
          yearsUsed: 4,
        },
        {
          lastUsed: 2019,
          skill: 'issue tracking',
          yearsUsed: 4,
        },
        {
          lastUsed: 2019,
          skill: 'knowledge base',
          yearsUsed: 4,
        },
        {
          lastUsed: 2013,
          score: 15.0,
          skill: 'documentation',
          yearsUsed: 12,
        },
        {
          lastUsed: 2013,
          score: 15.0,
          skill: 'consulting',
          yearsUsed: 8,
        },
        {
          lastUsed: 2013,
          score: 15.0,
          skill: 'engineering',
          yearsUsed: 8,
        },
        {
          lastUsed: 2013,
          score: 15.0,
          skill: 'network engineering',
          yearsUsed: 8,
        },
        {
          lastUsed: 2013,
          score: 15.0,
          skill: 'proposal writing',
          yearsUsed: 8,
        },
        {
          lastUsed: 2013,
          score: 15.0,
          skill: 'software deployment',
          yearsUsed: 8,
        },
        {
          lastUsed: 2013,
          score: 15.0,
          skill: 'writing',
          yearsUsed: 8,
        },
        {
          lastUsed: 2013,
          skill: 'network',
          yearsUsed: 8,
        },
        {
          lastUsed: 2013,
          skill: 'onshore',
          yearsUsed: 8,
        },
        {
          lastUsed: 2005,
          score: 15.0,
          skill: 'sales',
          yearsUsed: 4,
        },
        {
          lastUsed: 2005,
          skill: 'it infrastructure',
          yearsUsed: 4,
        },
        {
          score: 15.0,
          skill: 'infrastructure',
        },
      ],
      socialProfiles: [
        {
          icon_64: 'https://cdn-assets.workdigital.co.uk/icon/social/64/dice.png',
          source: 'Dice',
        },
      ],
      workPermitDocuments: ['US Citizenship'],
      workPermitLocations: ['US'],
      workPreferences: [
        {
          willingToRelocate: false,
        },
      ],
      yearsOfExperience: 19,
      securityAllowance: {
        status: false,
      },
      languages: [],
      citizenship: ['US'],
    },
    {
      city: 'Wimauma',
      country: 'United States',
      currentJobTitle: 'IT Project Manager',
      currentCompany: 'Publix',
      education: [
        {
          degree: 'Bachelors',
          location: 'Wimauma FL United States',
          org: 'Western Governors University',
        },
      ],
      experience: {
        current: {
          org: 'Publix',
          periodEnd: {
            day: 1,
            month: 6,
            year: 2020,
          },
          periodStart: {
            day: 1,
            month: 1,
            year: 2020,
          },
          title: 'IT Project Manager',
        },
        history: [
          {
            org: 'Publix',
            periodEnd: {
              day: 1,
              month: 6,
              year: 2020,
            },
            periodStart: {
              day: 1,
              month: 1,
              year: 2020,
            },
            title: 'IT Project Manager',
          },
          {
            org: 'USAA',
            periodEnd: {
              day: 1,
              month: 4,
              year: 2019,
            },
            periodStart: {
              day: 1,
              month: 12,
              year: 2016,
            },
            title: 'Sr. Program/Project Manager - Remote',
          },
          {
            location: 'Rockville MD United States',
            org: 'XA Systems',
            periodEnd: {
              day: 1,
              month: 10,
              year: 2016,
            },
            periodStart: {
              day: 1,
              month: 10,
              year: 2013,
            },
            title: 'Engineering Support Project Manager',
          },
          {
            location: 'Washington DC United States',
            org: 'Keno Kozie',
            periodEnd: {
              day: 1,
              month: 10,
              year: 2013,
            },
            periodStart: {
              day: 1,
              month: 4,
              year: 2013,
            },
            title: 'Network Engineer',
          },
          {
            location: 'Washington DC United States',
            org: 'Dickstein & Shapiro',
            periodEnd: {
              day: 1,
              month: 5,
              year: 2012,
            },
            periodStart: {
              day: 1,
              month: 4,
              year: 2012,
            },
            title: 'System Administrator',
          },
          {
            location: 'Rockville MD United States',
            org: 'The Treatment & Learning Centers',
            periodEnd: {
              day: 1,
              month: 2,
              year: 2012,
            },
            periodStart: {
              day: 1,
              month: 5,
              year: 2010,
            },
            title: 'Desktop Engineer',
          },
          {
            location: 'Arlington VA United States',
            org: 'FCA Technologies',
            periodEnd: {
              day: 1,
              month: 11,
              year: 2012,
            },
            periodStart: {
              day: 1,
              month: 8,
              year: 2012,
            },
            title: 'Remote Systems Engineer',
          },
        ],
      },
      firstName: 'Carl',
      fullName: 'Carl Jones',
      dateLastActive: '2020-07-02T05:57:26Z',
      dateResumeLastUpdated: '2020-07-02T15:56:34Z',
      desiredJobTitles: ['IT Manager - Remote'],
      hasEmail: true,
      hasPhone: true,
      id: 'de32af67b76c108cdb1b5dce1d3c7c1d57504108',
      legacyIds: [],
      isThirdParty: false,
      lastName: 'Jones',
      likelyToMove: true,
      likelyToMoveScore: 100.0,
      locations: [
        {
          city: 'Wimauma',
          country: 'United States',
          countryCode: 'US',
          latitude: 27.71253,
          longitude: -82.29898,
          region: 'Florida',
          source: 'dice',
          text: 'Wimauma, Florida US',
        },
        {
          city: 'Washington',
          country: 'United States',
          countryCode: 'US',
          latitude: 38.90719,
          longitude: -77.03687,
          region: 'District of Columbia',
          source: 'public',
          text: 'Washington, District of Columbia US',
        },
      ],
      region: 'Florida',
      skills: [
        {
          lastUsed: 2020,
          score: 15.0,
          skill: 'kanban',
          yearsUsed: 1,
        },
        {
          lastUsed: 2019,
          score: 30.0,
          skill: 'technical support',
          yearsUsed: 16,
        },
        {
          lastUsed: 2019,
          score: 15.0,
          skill: 'microsoft office',
          yearsUsed: 15,
        },
        {
          lastUsed: 2019,
          skill: 'hardware',
          yearsUsed: 15,
        },
        {
          lastUsed: 2019,
          skill: 'distribution',
          yearsUsed: 12,
        },
        {
          lastUsed: 2019,
          score: 15.0,
          skill: 'inspection',
          yearsUsed: 11,
        },
        {
          lastUsed: 2019,
          score: 15.0,
          skill: 'inventory',
          yearsUsed: 11,
        },
        {
          lastUsed: 2019,
          score: 15.0,
          skill: 'quality control',
          yearsUsed: 11,
        },
        {
          lastUsed: 2019,
          score: 15.0,
          skill: 'research',
          yearsUsed: 11,
        },
        {
          lastUsed: 2019,
          score: 30.0,
          skill: 'infrastructure',
          yearsUsed: 10,
        },
        {
          lastUsed: 2019,
          score: 15.0,
          skill: 'qa',
          yearsUsed: 9,
        },
        {
          lastUsed: 2019,
          score: 15.0,
          skill: 'training',
          yearsUsed: 9,
        },
        {
          lastUsed: 2019,
          skill: 'upgrades',
          yearsUsed: 9,
        },
        {
          lastUsed: 2019,
          skill: 'it infrastructure',
          yearsUsed: 8,
        },
        {
          lastUsed: 2019,
          skill: 'software',
          yearsUsed: 8,
        },
        {
          lastUsed: 2019,
          score: 30.0,
          skill: 'project management',
          yearsUsed: 7,
        },
        {
          lastUsed: 2019,
          score: 15.0,
          skill: 'agile',
          yearsUsed: 7,
        },
        {
          lastUsed: 2019,
          score: 15.0,
          skill: 'business analysis',
          yearsUsed: 7,
        },
        {
          lastUsed: 2019,
          score: 15.0,
          skill: 'change management',
          yearsUsed: 7,
        },
        {
          lastUsed: 2019,
          score: 15.0,
          skill: 'consulting',
          yearsUsed: 7,
        },
        {
          lastUsed: 2019,
          score: 15.0,
          skill: 'program management',
          yearsUsed: 7,
        },
        {
          lastUsed: 2019,
          skill: 'implementation',
          yearsUsed: 7,
        },
        {
          lastUsed: 2019,
          skill: 'it project management',
          yearsUsed: 7,
        },
        {
          lastUsed: 2019,
          skill: 'metrics',
          yearsUsed: 7,
        },
        {
          lastUsed: 2019,
          score: 15.0,
          skill: 'help desk management',
          yearsUsed: 6,
        },
        {
          lastUsed: 2019,
          score: 15.0,
          skill: 'it management',
          yearsUsed: 6,
        },
        {
          lastUsed: 2019,
          score: 15.0,
          skill: 'it operations',
          yearsUsed: 6,
        },
        {
          lastUsed: 2019,
          score: 15.0,
          skill: 'itil',
          yearsUsed: 6,
        },
        {
          lastUsed: 2019,
          score: 15.0,
          skill: 'sdlc',
          yearsUsed: 6,
        },
        {
          lastUsed: 2019,
          skill: 'cisco jabber',
          yearsUsed: 5,
        },
        {
          lastUsed: 2019,
          score: 15.0,
          skill: 'microsoft project',
          yearsUsed: 4,
        },
        {
          lastUsed: 2019,
          skill: 'scrum master',
          yearsUsed: 1,
        },
        {
          lastUsed: 2018,
          score: 15.0,
          skill: 'networking',
          yearsUsed: 7,
        },
        {
          lastUsed: 2017,
          skill: 'microsoft lync',
          yearsUsed: 5,
        },
        {
          lastUsed: 2016,
          skill: 'technician',
          yearsUsed: 15,
        },
        {
          lastUsed: 2016,
          score: 15.0,
          skill: 'microsoft windows',
          yearsUsed: 13,
        },
        {
          lastUsed: 2016,
          score: 15.0,
          skill: 'microsoft exchange',
          yearsUsed: 8,
        },
        {
          lastUsed: 2016,
          score: 15.0,
          skill: 'system administration',
          yearsUsed: 8,
        },
        {
          lastUsed: 2016,
          skill: 'network',
          yearsUsed: 8,
        },
        {
          lastUsed: 2016,
          score: 15.0,
          skill: 'active directory',
          yearsUsed: 7,
        },
        {
          lastUsed: 2016,
          score: 15.0,
          skill: 'desktop administration',
          yearsUsed: 7,
        },
        {
          lastUsed: 2016,
          score: 15.0,
          skill: 'avaya',
          yearsUsed: 5,
        },
        {
          lastUsed: 2016,
          score: 15.0,
          skill: 'engineering',
          yearsUsed: 5,
        },
        {
          lastUsed: 2016,
          skill: 'desktop',
          yearsUsed: 5,
        },
        {
          lastUsed: 2016,
          score: 15.0,
          skill: 'vmware',
          yearsUsed: 4,
        },
        {
          lastUsed: 2016,
          skill: 'airwatch',
          yearsUsed: 3,
        },
        {
          lastUsed: 2016,
          score: 15.0,
          skill: 'citrix xenapp',
          yearsUsed: 2,
        },
        {
          lastUsed: 2016,
          score: 15.0,
          skill: 'microsoft access',
          yearsUsed: 2,
        },
        {
          lastUsed: 2016,
          skill: 'firewall',
          yearsUsed: 2,
        },
        {
          lastUsed: 2015,
          skill: 'mobile management',
          yearsUsed: 4,
        },
        {
          lastUsed: 2014,
          skill: 'telecommuting',
          yearsUsed: 6,
        },
        {
          lastUsed: 2012,
          score: 15.0,
          skill: 'lotus notes',
          yearsUsed: 1,
        },
        {
          lastUsed: 0,
          score: 15.0,
          skill: 'network administration',
        },
        {
          lastUsed: 0,
          score: 15.0,
          skill: 'troubleshooting',
        },
        {
          lastUsed: 0,
          score: 15.0,
          skill: 'windows server',
        },
        {
          score: 15.0,
          skill: 'cisco',
        },
        {
          score: 15.0,
          skill: 'lync',
        },
        {
          score: 15.0,
          skill: 'management',
        },
        {
          score: 15.0,
          skill: 'scrum',
        },
      ],
      socialProfiles: [
        {
          icon_64: 'https://cdn-assets.workdigital.co.uk/icon/social/64/facebook.png',
          source: 'Facebook',
        },
        {
          icon_64: 'https://cdn-assets.workdigital.co.uk/icon/social/64/dice.png',
          source: 'Dice',
        },
        {
          icon_64: 'https://cdn-assets.workdigital.co.uk/icon/social/64/linkedin.png',
          source: 'Linkedin',
        },
        {
          icon_64: 'https://cdn-assets.workdigital.co.uk/icon/social/64/dice.png',
          source: 'Dice',
        },
      ],
      workPermitDocuments: ['US Citizenship'],
      workPermitLocations: ['US'],
      workPreferences: [
        {
          employmentType: ['Contract - Corp-to-Corp', 'Contract - W2', 'Full-time', 'Contract to Hire - W2', 'Contract to Hire - Corp-to-Corp'],
          hourlyRate: {
            currency: 'USD',
            max: 0,
            min: 60,
          },
          willingToRelocate: false,
          travelPreference: 50,
        },
        {
          employmentType: ['Contract - Corp-to-Corp', 'Contract - W2', 'Full-time', 'Contract to Hire - W2', 'Contract to Hire - Corp-to-Corp'],
          annualSalary: {
            currency: 'USD',
            max: 0,
            min: 125000,
          },
          willingToRelocate: false,
          travelPreference: 50,
        },
      ],
      yearsOfExperience: 10,
      securityAllowance: {
        status: false,
      },
      languages: [],
      citizenship: ['US'],
    },
  ],
  usage: {
    customerId: 145617,
    quota: 8333,
    viewsConsumed: 52,
    viewsRemaining: 8281,
  },
}
