module.exports = [
  {
    state: 'NE',
    education_level: "Associate's Degree (AA/AS/AAS)",
    experience_level: '3-5 years',
    client_ip: '64.253.187.169',
    zip: '68102',
    desired_compensation: '$25,000',
    last_name: 'Mason',
    email: 'jcbsmom83@gmail.com',
    city: 'Omaha',
    first_name: 'Tammy',
    language: 'en',
    job_title: 'Hr Assistant',
    candidate_source: 'lensa',
    target_id: 'af374d2bc148419abfb8af3118bcfa18',
  },
  {
    state: 'FL',
    education_level: 'High School Diploma',
    experience_level: 'Ten plus years',
    client_ip: '2601:58c:c500:7d1:d0c7:f4ce:1a32:8c4e',
    zip: '33336',
    desired_compensation: '$100,000',
    last_name: 'Patton',
    email: 'pattonalex@aol.com',
    city: 'Fort Lauderdale',
    first_name: 'Alex ',
    language: 'en',
    job_title: 'Regional Sales Manager',
    candidate_source: 'lensa',
    target_id: 'af374d2bc148419abfb8af3118bcfa18',
  },
  {
    state: 'WI',
    education_level: "Master's or Ph.D",
    experience_level: 'Ten plus years',
    client_ip: '2603:6000:d748:9570:4cdf:3ef9:bf9:f018',
    zip: '53188',
    desired_compensation: '$95,000',
    last_name: 'Binmahfouz',
    email: 'amarss16@icloud.com',
    city: 'Waukesha',
    first_name: 'Adnan',
    language: 'en',
    job_title: 'Sales Territory Manager',
    candidate_source: 'lensa',
    target_id: 'af374d2bc148419abfb8af3118bcfa18',
  },
  {
    state: 'OH',
    education_level: 'High School Diploma',
    experience_level: 'Ten plus years',
    client_ip: '2607:fb90:b471:6402:4830:b450:2f74:557e',
    zip: '44114',
    desired_compensation: '$45,000',
    last_name: 'Blaylock ',
    email: 'amblaylock@sbcglobal.net',
    city: 'Cleveland',
    first_name: 'April',
    language: 'en',
    job_title: 'Hr Assistant',
    candidate_source: 'lensa',
    target_id: 'af374d2bc148419abfb8af3118bcfa18',
  },
  {
    state: 'GA',
    client_ip: '2606:a000:1225:8f55:d4b2:d345:cfe6:8904',
    zip: '30334',
    last_name: 'Jennings',
    email: 'jenningspatrice1@gmail.com',
    city: 'Atlanta',
    first_name: 'Patrice',
    language: 'en',
    job_title: 'Talent Acquisition Manager',
    candidate_source: 'lensa',
    target_id: 'af374d2bc148419abfb8af3118bcfa18',
  },
  {
    state: 'MD',
    education_level: "Master's or Ph.D",
    experience_level: 'Ten plus years',
    client_ip: '71.178.161.147',
    zip: '20814',
    desired_compensation: '$255,000',
    last_name: 'NEOCLEOUS',
    email: 'gregoriosneokleous@gmail.com',
    city: 'Bethesda',
    first_name: 'GREGORIOS',
    language: 'en',
    job_title: 'Hr Consultant',
    candidate_source: 'lensa',
    target_id: 'af374d2bc148419abfb8af3118bcfa18',
  },
  {
    state: 'GA',
    client_ip: '2600:1700:1960:e8c0:b904:83c4:133f:67bb',
    zip: '30303',
    last_name: 'Thompson',
    email: 'teresat30009@gmail.com',
    city: 'Atlanta',
    first_name: 'Teresa',
    language: 'en',
    job_title: 'Talent Acquisition Manager',
    candidate_source: 'lensa',
    target_id: 'af374d2bc148419abfb8af3118bcfa18',
  },
  {
    state: 'CA',
    education_level: "Bachelor's Degree",
    experience_level: 'Ten plus years',
    client_ip: '2601:205:3:7b80:c83:bae3:d549:9a35',
    zip: '93612',
    desired_compensation: '$95,000',
    last_name: 'Dizon',
    email: 'susand37@yahoo.com',
    city: 'Clovis',
    first_name: 'Susan',
    language: 'en',
    job_title: 'RN',
    candidate_source: 'lensa',
    target_id: 'af374d2bc148419abfb8af3118bcfa18',
  },
  {
    state: 'MI',
    client_ip: '2600:1702:810:f9a0:9817:6b99:5d94:c3ac',
    zip: '48313',
    last_name: '',
    email: 'sherrygunter@sbcglobal.net',
    city: 'Sterling Heights',
    first_name: '',
    language: 'en',
    job_title: 'Hr Assistant',
    candidate_source: 'lensa',
    target_id: 'af374d2bc148419abfb8af3118bcfa18',
  },
  {
    state: 'MN',
    education_level: "Bachelor's Degree",
    experience_level: '6-10 years',
    client_ip: '2601:442:4580:65e0:a1ab:8ff8:ae21:58ec',
    zip: '55415',
    desired_compensation: '$65,000',
    last_name: '',
    email: 'jpburns30@gmail.com',
    city: 'Minneapolis',
    first_name: '',
    language: 'en',
    job_title: 'Regional Sales Manager',
    candidate_source: 'lensa',
    target_id: 'af374d2bc148419abfb8af3118bcfa18',
  },
  {
    state: 'MO',
    education_level: 'High School Diploma',
    experience_level: '1-3 years',
    client_ip: '2607:fb90:387a:ece3:d45d:e45e:bef7:7e4d',
    zip: '63026',
    desired_compensation: '$60,000',
    last_name: 'Kent ',
    email: 'tisha.kent@yahoo.com',
    city: 'Fenton',
    first_name: 'Tisha ',
    language: 'en',
    job_title: 'CDL A Driver',
    candidate_source: 'lensa',
    target_id: 'af374d2bc148419abfb8af3118bcfa18',
  },
  {
    state: 'NC',
    education_level: "Bachelor's Degree",
    experience_level: '6-10 years',
    client_ip: '172.10.26.200',
    zip: '28105',
    desired_compensation: '$90,000',
    last_name: 'Walton ',
    email: 'alisiawalton@gmail.com',
    city: 'Matthews',
    first_name: 'Alisia',
    language: 'en',
    job_title: 'Hr',
    candidate_source: 'lensa',
    target_id: 'af374d2bc148419abfb8af3118bcfa18',
  },
  {
    state: 'VA',
    client_ip: '96.244.67.153',
    zip: '20190',
    last_name: 'Egwom',
    email: 'begwom24@yahoo.com',
    city: 'Reston',
    first_name: 'Brian',
    language: 'en',
    job_title: 'Cloud Engineer',
    candidate_source: 'lensa',
    target_id: 'af374d2bc148419abfb8af3118bcfa18',
  },
  {
    state: 'PA',
    client_ip: '73.13.44.117',
    zip: '19107',
    last_name: 'goodman',
    email: 'mag1915@comcast.net',
    city: 'Philadelphia',
    first_name: 'mark',
    language: 'en',
    job_title: 'Senior Sales Manager',
    candidate_source: 'lensa',
    target_id: 'af374d2bc148419abfb8af3118bcfa18',
  },
  {
    state: 'FL',
    client_ip: '2601:480:4102:fbd0:30b9:5690:9be:d75c',
    zip: '32202',
    last_name: 'Wooten',
    email: 'sbyronwooten@gmail.com',
    city: 'Jacksonville',
    first_name: 'Samuel',
    language: 'en',
    job_title: 'Hr Manager',
    candidate_source: 'lensa',
    target_id: 'af374d2bc148419abfb8af3118bcfa18',
  },
  {
    state: 'MA',
    education_level: "Associate's Degree (AA/AS/AAS)",
    experience_level: 'Less than 1 year',
    client_ip: '2600:6c64:637f:f832:a580:8b5:8181:d9d7',
    zip: '02139',
    desired_compensation: '$35,000',
    last_name: 'Ndikidjang',
    email: 'juniorndikidjang2013@hotmail.com',
    city: 'Cambridge',
    first_name: 'Junior',
    language: 'en',
    job_title: 'Hr Manager',
    candidate_source: 'lensa',
    target_id: 'af374d2bc148419abfb8af3118bcfa18',
  },
  {
    state: 'VA',
    client_ip: '65.202.77.98',
    zip: '22030',
    last_name: 'Ritenour',
    email: 'kwolfie79@gmail.com',
    city: 'Fairfax',
    first_name: 'Kristine',
    language: 'en',
    job_title: 'Hr Coordinator',
    candidate_source: 'lensa',
    target_id: 'af374d2bc148419abfb8af3118bcfa18',
  },
  {
    state: 'NJ',
    client_ip: '2600:1001:b01b:1a9c:900c:18ba:e8c5:a9cb',
    zip: '07029',
    last_name: '',
    email: 'leitchcarlisha307@gmail.com',
    city: 'East Newark',
    first_name: '',
    language: 'en',
    job_title: 'Hr Assistant',
    candidate_source: 'lensa',
    target_id: 'af374d2bc148419abfb8af3118bcfa18',
  },
  {
    state: 'TX',
    education_level: "Bachelor's Degree",
    experience_level: 'Ten plus years',
    client_ip: '2601:2c4:c500:99d0:75c4:4259:6cc7:e95e',
    resume: {
      download_url:
        'https://api.lensa.com/coreg/v1/download-resume?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6IjFmZGM3Y2MyMjQzYTliN2RlMTNiMWRkYzAwNjVhMTQ3LTE1NDE5IiwibmFtZSI6IlJlc3VtZSBOb3ZlbWJlciAyMDE5KGRvY3gpLmRvYyIsInR5cGUiOiJhcHBsaWNhdGlvbi92bmQub3BlbnhtbGZvcm1hdHMtb2ZmaWNlZG9jdW1lbnQud29yZHByb2Nlc3NpbmdtbC5kb2N1bWVudCIsInZhcmlhbnQiOiJvcmlnaW5hbCIsImV4cCI6MTU5MzM1OTMyMX0.r-A6Ky_sdm1sQugZ-whujx6_WJe3tYH3Ymk-mp7VmhI',
    },
    zip: '77002',
    desired_compensation: '$40,000',
    parsed_resume: {
      download_url:
        'https://api.lensa.com/coreg/v1/download-resume?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6IjFmZGM3Y2MyMjQzYTliN2RlMTNiMWRkYzAwNjVhMTQ3LTE1NDE5IiwibmFtZSI6IlJlc3VtZSBOb3ZlbWJlciAyMDE5KGRvY3gpLmRvYy54bWwiLCJ0eXBlIjoidGV4dC94bWwiLCJ2YXJpYW50IjoicGFyc2VkIiwiZXhwIjoxNTkzMzU5MzIxfQ.f7YYybekLIp1QCufthfE9_2FoffzAXg1JvfGhA8GlQI',
    },
    last_name: 'Powers',
    email: 'jopow203@aol.com',
    city: 'Houston',
    first_name: 'Joel',
    language: 'en',
    job_title: 'Hr Coordinator',
    candidate_source: 'lensa',
    target_id: '375e3fb986124c58bbff665dfe115444',
  },
  {
    state: 'NJ',
    education_level: "Associate's Degree (AA/AS/AAS)",
    experience_level: 'Ten plus years',
    client_ip: '2600:1002:b118:1d24:cf60:9407:9d5:5556',
    resume: {
      download_url:
        'https://api.lensa.com/coreg/v1/download-resume?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6Ijc1OWNlYTJiMWFjZDYyOGMwYTYyZDAyMmZmOWRhNzlmLTI1OTQ2MCIsIm5hbWUiOiJrZWFybnMuY2hhcmxlcy5wZGYiLCJ0eXBlIjoiYXBwbGljYXRpb24vcGRmIiwidmFyaWFudCI6Im9yaWdpbmFsIiwiZXhwIjoxNTkzMzU5MzIxfQ.X3MinncNUOJSw2LVgh6sP66HmPBmKjhSgJyTTDwYtsQ',
    },
    zip: '08002',
    desired_compensation: '$255,000',
    parsed_resume: {
      download_url:
        'https://api.lensa.com/coreg/v1/download-resume?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6Ijc1OWNlYTJiMWFjZDYyOGMwYTYyZDAyMmZmOWRhNzlmLTI1OTQ2MCIsIm5hbWUiOiJrZWFybnMuY2hhcmxlcy5wZGYueG1sIiwidHlwZSI6InRleHQveG1sIiwidmFyaWFudCI6InBhcnNlZCIsImV4cCI6MTU5MzM1OTMyMX0.8SV3GKJpmUQ4hncOJ5vRUeL8iVlBElEWMy-8fpdSYlk',
    },
    last_name: 'kearns',
    email: 'ckearns3@gmail.com',
    city: 'Cherry Hill',
    first_name: 'charles',
    language: 'en',
    job_title: 'General Sales Manager',
    candidate_source: 'lensa',
    target_id: '375e3fb986124c58bbff665dfe115444',
  },
  {
    state: 'OR',
    education_level: 'High School Diploma',
    experience_level: 'Ten plus years',
    client_ip: '2601:1c2:4c01:34df:c5:e0d5:239c:3b5a',
    resume: {
      download_url:
        'https://api.lensa.com/coreg/v1/download-resume?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6IjBjYTgyMzM1NzY5NmVjM2RlZmE2NzNiN2ViM2E3MDUzLTgxMTIxIiwibmFtZSI6IkRvbiBKYWNveSBSZXN1bWVzICAyMDE5KGRvY3gpLmRvYyIsInR5cGUiOiJhcHBsaWNhdGlvbi92bmQub3BlbnhtbGZvcm1hdHMtb2ZmaWNlZG9jdW1lbnQud29yZHByb2Nlc3NpbmdtbC5kb2N1bWVudCIsInZhcmlhbnQiOiJvcmlnaW5hbCIsImV4cCI6MTU5MzM1OTMyMX0.M16oQX18dri4zjN450GXE6Uur9kf-oUBiWrM1PzjxyU',
    },
    zip: '97201',
    desired_compensation: '$45,000',
    parsed_resume: {
      download_url:
        'https://api.lensa.com/coreg/v1/download-resume?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6IjBjYTgyMzM1NzY5NmVjM2RlZmE2NzNiN2ViM2E3MDUzLTgxMTIxIiwibmFtZSI6IkRvbiBKYWNveSBSZXN1bWVzICAyMDE5KGRvY3gpLmRvYy54bWwiLCJ0eXBlIjoidGV4dC94bWwiLCJ2YXJpYW50IjoicGFyc2VkIiwiZXhwIjoxNTkzMzU5MzIxfQ.yy_wRFkxmi1Iu9NcByjla0d_BTRCVcwqQwnlLzcRWwM',
    },
    last_name: 'Jacoy ',
    email: 'dejagency@comcast.net',
    city: 'Portland',
    first_name: 'Donald ',
    language: 'en',
    job_title: 'Territory Manager',
    candidate_source: 'lensa',
    target_id: '375e3fb986124c58bbff665dfe115444',
  },
  {
    state: 'FL',
    education_level: "Bachelor's Degree",
    experience_level: 'Ten plus years',
    client_ip: '23.252.207.107',
    resume: {
      download_url:
        'https://api.lensa.com/coreg/v1/download-resume?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6Ijk4YmQ0NjI0YjE2ZDZkN2RhNGY3ZGMxZjc0YTc1NWZjLTIxMTYyIiwibmFtZSI6IkNWIE1BUklTT0wgIE9DSE9BIFdJVEggQ0hJTEQgQ0FSRSBJTkZPUk1BVElPTiAoMikoZG9jeCkuZG9jIiwidHlwZSI6ImFwcGxpY2F0aW9uL3ZuZC5vcGVueG1sZm9ybWF0cy1vZmZpY2Vkb2N1bWVudC53b3JkcHJvY2Vzc2luZ21sLmRvY3VtZW50IiwidmFyaWFudCI6Im9yaWdpbmFsIiwiZXhwIjoxNTkzMzU5MzIxfQ.YoFRTEEskNhQ5ooAlBM0CxWbfwarJ2KHwuXeuE-0g2g',
    },
    zip: '33128',
    desired_compensation: '$45,000',
    parsed_resume: {
      download_url:
        'https://api.lensa.com/coreg/v1/download-resume?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6Ijk4YmQ0NjI0YjE2ZDZkN2RhNGY3ZGMxZjc0YTc1NWZjLTIxMTYyIiwibmFtZSI6IkNWIE1BUklTT0wgIE9DSE9BIFdJVEggQ0hJTEQgQ0FSRSBJTkZPUk1BVElPTiAoMikoZG9jeCkuZG9jLnhtbCIsInR5cGUiOiJ0ZXh0L3htbCIsInZhcmlhbnQiOiJwYXJzZWQiLCJleHAiOjE1OTMzNTkzMjF9.OERlNcJ30ltwdAoqItMXiTcpwMxzgmj52YUuuM0D-SY',
    },
    last_name: 'Viloria de Ochoa',
    email: 'marisoldeochoa@gmail.com',
    city: 'Miami',
    first_name: 'Marisol',
    language: 'en',
    job_title: 'Hr Generalist',
    candidate_source: 'lensa',
    target_id: '375e3fb986124c58bbff665dfe115444',
  },
  {
    state: 'TX',
    education_level: "Master's or Ph.D",
    experience_level: 'Ten plus years',
    client_ip: '2600:6c52:7a80:a457:ac27:ed73:af36:2570',
    resume: {
      download_url:
        'https://api.lensa.com/coreg/v1/download-resume?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6IjI5Y2Y5ODI3NWJmYTM4ZjBmMDE0ODc1MWIzMzIzZWY0LTMxOTkwIiwibmFtZSI6Ik1pY2hlbGxlIExlUGFnZSBSZXN1bWUoZG9jeCkuZG9jIiwidHlwZSI6ImFwcGxpY2F0aW9uL3ZuZC5vcGVueG1sZm9ybWF0cy1vZmZpY2Vkb2N1bWVudC53b3JkcHJvY2Vzc2luZ21sLmRvY3VtZW50IiwidmFyaWFudCI6Im9yaWdpbmFsIiwiZXhwIjoxNTkzMzU5MzIxfQ.y9dknBBZWe2QCmMuMhk9Xo2lp-p2yMIrqc8nKLX7Jwc',
    },
    zip: '79901',
    desired_compensation: '$25,000',
    parsed_resume: {
      download_url:
        'https://api.lensa.com/coreg/v1/download-resume?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6IjI5Y2Y5ODI3NWJmYTM4ZjBmMDE0ODc1MWIzMzIzZWY0LTMxOTkwIiwibmFtZSI6Ik1pY2hlbGxlIExlUGFnZSBSZXN1bWUoZG9jeCkuZG9jLnhtbCIsInR5cGUiOiJ0ZXh0L3htbCIsInZhcmlhbnQiOiJwYXJzZWQiLCJleHAiOjE1OTMzNTkzMjF9.2GutQmTotniBTdEBRtfRxvmjslNm5zMZBGk1JOPs-g8',
    },
    last_name: 'LePage',
    email: 'lepagemichelle@hotmail.com',
    city: 'El Paso',
    first_name: 'Michelle',
    language: 'en',
    job_title: 'Hr Generalist',
    candidate_source: 'lensa',
    target_id: '375e3fb986124c58bbff665dfe115444',
  },
  {
    state: 'GA',
    education_level: "Bachelor's Degree",
    experience_level: 'Ten plus years',
    client_ip: '155.186.162.135',
    resume: {
      download_url:
        'https://api.lensa.com/coreg/v1/download-resume?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6IjM0NjVhYjkyM2YxOTAxN2ZlNDJjZWFkNTlkZTNmYjYyLTI5NTIzIiwibmFtZSI6IkxhU2hhd24gV2ltYmVybHkgQihkb2N4KS5kb2MiLCJ0eXBlIjoiYXBwbGljYXRpb24vdm5kLm9wZW54bWxmb3JtYXRzLW9mZmljZWRvY3VtZW50LndvcmRwcm9jZXNzaW5nbWwuZG9jdW1lbnQiLCJ2YXJpYW50Ijoib3JpZ2luYWwiLCJleHAiOjE1OTMzNTkzMjF9.0FYwSbKnIkEMVU7SxSzrZ2Ym48YrxODHMNmiNj0bSys',
    },
    zip: '30303',
    desired_compensation: '$60,000',
    parsed_resume: {
      download_url:
        'https://api.lensa.com/coreg/v1/download-resume?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6IjM0NjVhYjkyM2YxOTAxN2ZlNDJjZWFkNTlkZTNmYjYyLTI5NTIzIiwibmFtZSI6IkxhU2hhd24gV2ltYmVybHkgQihkb2N4KS5kb2MueG1sIiwidHlwZSI6InRleHQveG1sIiwidmFyaWFudCI6InBhcnNlZCIsImV4cCI6MTU5MzM1OTMyMX0.Z4h2BN9yTEXbbG9QWiLIrpRO5_417DjvxVq00GWxsak',
    },
    last_name: 'WIMBERLY',
    email: 'lawimberly23@gmail.com',
    city: 'Atlanta',
    first_name: 'LASHAWN',
    language: 'en',
    job_title: 'Hr Manager',
    candidate_source: 'lensa',
    target_id: '375e3fb986124c58bbff665dfe115444',
  },
  {
    state: 'AZ',
    client_ip: '2600:8800:1000:44c0:d87f:299e:7aa7:f98f',
    resume: {
      download_url:
        'https://api.lensa.com/coreg/v1/download-resume?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6Ijk5NmU1N2YwNDg5OWI1YThmYTMwODFlZGUxOTM1M2M0LTEzMDE0NyIsIm5hbWUiOiJTaW5kaHVqYSBBbmFudGggcmVzdW1lLnBkZiIsInR5cGUiOiJhcHBsaWNhdGlvbi9wZGYiLCJ2YXJpYW50Ijoib3JpZ2luYWwiLCJleHAiOjE1OTMzNTkzMjF9.LIyUgX2WXeIC5o3dNcepkSdUFD46JoWAo7k4qzFz-3g',
    },
    zip: '85225',
    parsed_resume: {
      download_url:
        'https://api.lensa.com/coreg/v1/download-resume?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6Ijk5NmU1N2YwNDg5OWI1YThmYTMwODFlZGUxOTM1M2M0LTEzMDE0NyIsIm5hbWUiOiJTaW5kaHVqYSBBbmFudGggcmVzdW1lLnBkZi54bWwiLCJ0eXBlIjoidGV4dC94bWwiLCJ2YXJpYW50IjoicGFyc2VkIiwiZXhwIjoxNTkzMzU5MzIxfQ.UgKTooeca5necK3GGiLu7NmqYkxXLpjOQCmxjW00S6U',
    },
    last_name: 'Ananth',
    email: 'sindhuja221986@gmail.com',
    city: 'Chandler',
    first_name: 'Sindhuja',
    language: 'en',
    job_title: 'Hr Administrator',
    candidate_source: 'lensa',
    target_id: '375e3fb986124c58bbff665dfe115444',
  },
  {
    state: 'OH',
    education_level: "Associate's Degree (AA/AS/AAS)",
    experience_level: 'Ten plus years',
    client_ip: '104.231.108.121',
    resume: {
      download_url:
        'https://api.lensa.com/coreg/v1/download-resume?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6IjdhZGI1YTcwMTFkOGE5NDEzOWRkNzdkM2NhMDk3NmMwLTgyOTYzIiwibmFtZSI6IlJlc3VtZSAtIEhvd2FyZCBEaWVsbWFuLnBkZiIsInR5cGUiOiJhcHBsaWNhdGlvbi9wZGYiLCJ2YXJpYW50Ijoib3JpZ2luYWwiLCJleHAiOjE1OTMzNTkzMjF9.ZTwttfo7cUUwOeZg-fVU2dlqipVjmEwzdtO-0YlM8_A',
    },
    zip: '44114',
    desired_compensation: '$65,000',
    parsed_resume: {
      download_url:
        'https://api.lensa.com/coreg/v1/download-resume?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6IjdhZGI1YTcwMTFkOGE5NDEzOWRkNzdkM2NhMDk3NmMwLTgyOTYzIiwibmFtZSI6IlJlc3VtZSAtIEhvd2FyZCBEaWVsbWFuLnBkZi54bWwiLCJ0eXBlIjoidGV4dC94bWwiLCJ2YXJpYW50IjoicGFyc2VkIiwiZXhwIjoxNTkzMzU5MzIxfQ.onP71aw5R2n8Y6XMDoWpTq-mn0yanOmnH13Sh1pS3rE',
    },
    last_name: 'Dielman',
    email: 'hdielman@aol.com',
    city: 'Cleveland',
    first_name: 'Howard',
    language: 'en',
    job_title: 'Regional Sales Manager',
    candidate_source: 'lensa',
    target_id: '375e3fb986124c58bbff665dfe115444',
  },
  {
    state: 'AZ',
    education_level: "Master's or Ph.D",
    experience_level: 'Ten plus years',
    client_ip: '2600:1011:b169:cabb:35dc:3edd:d34f:546c',
    resume: {
      download_url:
        'https://api.lensa.com/coreg/v1/download-resume?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6IjNmZjc5MzkwOWI2YjA0Yjk3NjQ1NjAyYjk0YjU2ZjM3LTEzMjI3IiwibmFtZSI6IkdDLTIwMjAoZG9jeCkuZG9jIiwidHlwZSI6ImFwcGxpY2F0aW9uL3ZuZC5vcGVueG1sZm9ybWF0cy1vZmZpY2Vkb2N1bWVudC53b3JkcHJvY2Vzc2luZ21sLmRvY3VtZW50IiwidmFyaWFudCI6Im9yaWdpbmFsIiwiZXhwIjoxNTkzMzU5MzIxfQ.9rK9sQ0XSXQbJNbCJFHwnvmOY4P49yBY0Nl8W3wfxLc',
    },
    zip: '85003',
    desired_compensation: '$65,000',
    parsed_resume: {
      download_url:
        'https://api.lensa.com/coreg/v1/download-resume?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6IjNmZjc5MzkwOWI2YjA0Yjk3NjQ1NjAyYjk0YjU2ZjM3LTEzMjI3IiwibmFtZSI6IkdDLTIwMjAoZG9jeCkuZG9jLnhtbCIsInR5cGUiOiJ0ZXh0L3htbCIsInZhcmlhbnQiOiJwYXJzZWQiLCJleHAiOjE1OTMzNTkzMjF9.zHOXHDwVVpbakX9Lff1tRiNTI2vXMfDpnGcfgWV1__I',
    },
    last_name: 'Cooper',
    email: 'azldshark@me.com',
    city: 'Phoenix',
    first_name: 'Grant',
    language: 'en',
    job_title: 'Regional Sales Manager',
    candidate_source: 'lensa',
    target_id: '375e3fb986124c58bbff665dfe115444',
  },
  {
    state: 'LA',
    education_level: "Master's or Ph.D",
    experience_level: 'Ten plus years',
    client_ip: '184.179.120.34',
    resume: {
      download_url:
        'https://api.lensa.com/coreg/v1/download-resume?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6ImQxOTY2MDE0NmUyYjUzMTkxZDc4MzEyM2RjYzA3ZGUyLTcxNTg3IiwibmFtZSI6IlREQXJlc3VtZTIwMjAoZG9jeCkuZG9jIiwidHlwZSI6ImFwcGxpY2F0aW9uL3ZuZC5vcGVueG1sZm9ybWF0cy1vZmZpY2Vkb2N1bWVudC53b3JkcHJvY2Vzc2luZ21sLmRvY3VtZW50IiwidmFyaWFudCI6Im9yaWdpbmFsIiwiZXhwIjoxNTkzMzU5MzIxfQ.vz39TjPL1jfHjtinlVDiUzRr1L9SliFjoYwA2xComBs',
    },
    zip: '70005',
    desired_compensation: '$130,000',
    parsed_resume: {
      download_url:
        'https://api.lensa.com/coreg/v1/download-resume?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6ImQxOTY2MDE0NmUyYjUzMTkxZDc4MzEyM2RjYzA3ZGUyLTcxNTg3IiwibmFtZSI6IlREQXJlc3VtZTIwMjAoZG9jeCkuZG9jLnhtbCIsInR5cGUiOiJ0ZXh0L3htbCIsInZhcmlhbnQiOiJwYXJzZWQiLCJleHAiOjE1OTMzNTkzMjF9.wdUfp9Sd_eRLEdhnKdVgbYwFfaGOeU7paLJ-7VNpCZ4',
    },
    last_name: 'Armbruster',
    email: 'tdarmbruster@gmail.com',
    city: 'Metairie',
    first_name: 'Tonya',
    language: 'en',
    job_title: 'Hr',
    candidate_source: 'lensa',
    target_id: '375e3fb986124c58bbff665dfe115444',
  },
  {
    state: 'TX',
    education_level: "Master's or Ph.D",
    experience_level: 'Ten plus years',
    client_ip: '47.188.134.197',
    resume: {
      download_url:
        'https://api.lensa.com/coreg/v1/download-resume?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6IjU3NTg1MjA2NWU4NzM4NmMxNWJiMDY5MDE1ZjRiYmY0LTMwNjE1IiwibmFtZSI6IlN1c2FuIFJlc3NhIC0gUmVzdW1lIC0gUmV2IDUtOC0yMCBjb3B5KGRvY3gpLmRvYyIsInR5cGUiOiJhcHBsaWNhdGlvbi92bmQub3BlbnhtbGZvcm1hdHMtb2ZmaWNlZG9jdW1lbnQud29yZHByb2Nlc3NpbmdtbC5kb2N1bWVudCIsInZhcmlhbnQiOiJvcmlnaW5hbCIsImV4cCI6MTU5MzM1OTMyMX0.Z3XDzf1YNiyM5bx0uKFGVB7d00E5a0jmdF5Zd_-1VUU',
    },
    zip: '75074',
    desired_compensation: '$60,000',
    parsed_resume: {
      download_url:
        'https://api.lensa.com/coreg/v1/download-resume?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6IjU3NTg1MjA2NWU4NzM4NmMxNWJiMDY5MDE1ZjRiYmY0LTMwNjE1IiwibmFtZSI6IlN1c2FuIFJlc3NhIC0gUmVzdW1lIC0gUmV2IDUtOC0yMCBjb3B5KGRvY3gpLmRvYy54bWwiLCJ0eXBlIjoidGV4dC94bWwiLCJ2YXJpYW50IjoicGFyc2VkIiwiZXhwIjoxNTkzMzU5MzIxfQ.m-xod-SJxnjhI_kQe3L_JT--VQNfu70RslrjdbNgTcM',
    },
    last_name: 'Ressa',
    email: 'susan.ressa@live.com',
    city: 'Plano',
    first_name: 'Susan',
    language: 'en',
    job_title: 'Hr Manager',
    candidate_source: 'lensa',
    target_id: '375e3fb986124c58bbff665dfe115444',
  },
  {
    state: 'CO',
    education_level: "Master's or Ph.D",
    experience_level: 'Ten plus years',
    client_ip: '2601:282:4303:8de0:515a:e703:7622:2a8a',
    resume: {
      download_url:
        'https://api.lensa.com/coreg/v1/download-resume?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6IjVhYTZiMDMzNWQ4OWZmMjEwN2U5NWU3ZTI5YmNmMzM1LTkzOTQ2IiwibmFtZSI6IlN0YWNleSBCZWhsaW5nIFJlc3VtZSB4LnBkZiIsInR5cGUiOiJhcHBsaWNhdGlvbi9wZGYiLCJ2YXJpYW50Ijoib3JpZ2luYWwiLCJleHAiOjE1OTMzNTkzMjF9.42P-5j8jXu1XRiw3RZvjvN0el4M79YI055n_ExVTJz8',
    },
    zip: '80112',
    desired_compensation: '$50,000',
    parsed_resume: {
      download_url:
        'https://api.lensa.com/coreg/v1/download-resume?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6IjVhYTZiMDMzNWQ4OWZmMjEwN2U5NWU3ZTI5YmNmMzM1LTkzOTQ2IiwibmFtZSI6IlN0YWNleSBCZWhsaW5nIFJlc3VtZSB4LnBkZi54bWwiLCJ0eXBlIjoidGV4dC94bWwiLCJ2YXJpYW50IjoicGFyc2VkIiwiZXhwIjoxNTkzMzU5MzIxfQ.iA63Y-anHJdnIEPnqDS6EVHZOY1hoVlSoE7ur1aHGfg',
    },
    last_name: 'behling',
    email: 'staceybehling@gmail.com',
    city: 'Centennial',
    first_name: 'stacey',
    language: 'en',
    job_title: 'Hr Manager',
    candidate_source: 'lensa',
    target_id: '375e3fb986124c58bbff665dfe115444',
  },
  {
    state: 'OK',
    education_level: "Bachelor's Degree",
    experience_level: 'Ten plus years',
    client_ip: '70.184.31.2',
    resume: {
      download_url:
        'https://api.lensa.com/coreg/v1/download-resume?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6IjBlNDc4MDE0Nzc3NzU2ZTI4Zjg2Y2RkYmZmMDc5MTZkLTE2NjA5IiwibmFtZSI6IkphbmV0IEQoZG9jeCkuZG9jIiwidHlwZSI6ImFwcGxpY2F0aW9uL3ZuZC5vcGVueG1sZm9ybWF0cy1vZmZpY2Vkb2N1bWVudC53b3JkcHJvY2Vzc2luZ21sLmRvY3VtZW50IiwidmFyaWFudCI6Im9yaWdpbmFsIiwiZXhwIjoxNTkzMzU5MzIxfQ.LzlygMzfq5LEJFNCPvFVu6O2W13KUsBcQv-y89lbZ_A',
    },
    zip: '74103',
    desired_compensation: '$85,000',
    parsed_resume: {
      download_url:
        'https://api.lensa.com/coreg/v1/download-resume?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6IjBlNDc4MDE0Nzc3NzU2ZTI4Zjg2Y2RkYmZmMDc5MTZkLTE2NjA5IiwibmFtZSI6IkphbmV0IEQoZG9jeCkuZG9jLnhtbCIsInR5cGUiOiJ0ZXh0L3htbCIsInZhcmlhbnQiOiJwYXJzZWQiLCJleHAiOjE1OTMzNTkzMjF9.L_UA6D5g7aaMXDGa_nu0LyjbO_f2sNFwbN1RCA92FFQ',
    },
    last_name: 'Lowe',
    email: 'jlowe3300@gmail.com',
    city: 'Tulsa',
    first_name: 'Janet',
    language: 'en',
    job_title: 'Hr Generalist',
    candidate_source: 'lensa',
    target_id: '375e3fb986124c58bbff665dfe115444',
  },
  {
    state: 'KS',
    education_level: "Bachelor's Degree",
    experience_level: 'Ten plus years',
    client_ip: '187.194.45.152',
    resume: {
      download_url:
        'https://api.lensa.com/coreg/v1/download-resume?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6IjAxYzY5M2ZjMzM4YzA3MWYxYWFiOTkxYzhkOTcwY2YyLTEwMDkwMSIsIm5hbWUiOiJHUkFCSUVMIFRFUlJJUVVFWiAtIE9wZXJhdGlvbnMgRW5naW5lZXIgMjAyMC5wZGYiLCJ0eXBlIjoiYXBwbGljYXRpb24vcGRmIiwidmFyaWFudCI6Im9yaWdpbmFsIiwiZXhwIjoxNTkzMzU5MzIxfQ.U8NRRmAfz_0deh2SutWxIzchHe-fm4VL2rnE6dzfJuw',
    },
    zip: '66053',
    desired_compensation: '$140,000',
    parsed_resume: {
      download_url:
        'https://api.lensa.com/coreg/v1/download-resume?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6IjAxYzY5M2ZjMzM4YzA3MWYxYWFiOTkxYzhkOTcwY2YyLTEwMDkwMSIsIm5hbWUiOiJHUkFCSUVMIFRFUlJJUVVFWiAtIE9wZXJhdGlvbnMgRW5naW5lZXIgMjAyMC5wZGYueG1sIiwidHlwZSI6InRleHQveG1sIiwidmFyaWFudCI6InBhcnNlZCIsImV4cCI6MTU5MzM1OTMyMX0.uy1T4aDyFnafqXXxvIi-jGAABOT_dq2xEiSmdeMVOIo',
    },
    last_name: 'Terriquez Camarena',
    email: 'grabielt@hotmail.com',
    city: 'Louisburg',
    first_name: 'Grabiel',
    language: 'en',
    job_title: 'CDL A Driver',
    candidate_source: 'lensa',
    target_id: '375e3fb986124c58bbff665dfe115444',
  },
  {
    state: 'CO',
    education_level: "Bachelor's Degree",
    experience_level: 'Ten plus years',
    client_ip: '199.245.156.254',
    resume: {
      download_url:
        'https://api.lensa.com/coreg/v1/download-resume?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6IjJiOTEyNjJiY2M2ZmYzNjE1OTQzY2U2OTFiMTk5YjBkLTE0MDIzNCIsIm5hbWUiOiJNYXR0IEx1Y2VybyBSZXN1bWUganVuZTIwMjAucGRmIiwidHlwZSI6ImFwcGxpY2F0aW9uL3BkZiIsInZhcmlhbnQiOiJvcmlnaW5hbCIsImV4cCI6MTU5MzM1OTMyMX0.yujZUCQzAGxfGf37R3GVQzlL2Hai4Sa0fn91ySm9Cj4',
    },
    zip: '80903',
    desired_compensation: '$40,000',
    parsed_resume: {
      download_url:
        'https://api.lensa.com/coreg/v1/download-resume?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6IjJiOTEyNjJiY2M2ZmYzNjE1OTQzY2U2OTFiMTk5YjBkLTE0MDIzNCIsIm5hbWUiOiJNYXR0IEx1Y2VybyBSZXN1bWUganVuZTIwMjAucGRmLnhtbCIsInR5cGUiOiJ0ZXh0L3htbCIsInZhcmlhbnQiOiJwYXJzZWQiLCJleHAiOjE1OTMzNTkzMjF9.Y87KVwP5dJOFv0nHATAbmTFQadlzHFp8fPv-t5olyEI',
    },
    last_name: 'Lucero',
    email: 'mlucero523@msn.com',
    city: 'Colorado Springs',
    first_name: 'Matt',
    language: 'en',
    job_title: 'Hr Assistant',
    candidate_source: 'lensa',
    target_id: '375e3fb986124c58bbff665dfe115444',
  },
  {
    state: 'FL',
    education_level: "Master's or Ph.D",
    experience_level: 'Ten plus years',
    client_ip: '184.91.103.137',
    resume: {
      download_url:
        'https://api.lensa.com/coreg/v1/download-resume?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6IjJlOTFjMTljMzQ4YzI0MzVmZmQyYjY3OTBlZDZjZWEzLTQwODQ3IiwibmFtZSI6IkNWLiBBZHJyaWEgR2FyY2lhLnBkZiIsInR5cGUiOiJhcHBsaWNhdGlvbi9wZGYiLCJ2YXJpYW50Ijoib3JpZ2luYWwiLCJleHAiOjE1OTMzNTkzMjF9.Sm60L9G3X80QjZ3R4IWT-c5zjJ2HeGHJsQVaxIx0Y_A',
    },
    zip: '33166',
    desired_compensation: '$50,000',
    parsed_resume: {
      download_url:
        'https://api.lensa.com/coreg/v1/download-resume?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6IjJlOTFjMTljMzQ4YzI0MzVmZmQyYjY3OTBlZDZjZWEzLTQwODQ3IiwibmFtZSI6IkNWLiBBZHJyaWEgR2FyY2lhLnBkZi54bWwiLCJ0eXBlIjoidGV4dC94bWwiLCJ2YXJpYW50IjoicGFyc2VkIiwiZXhwIjoxNTkzMzU5MzIxfQ.io4oTFyKVRO-_H2FuYc6R7AHm-SPldTFT-SAqaNOiHc',
    },
    last_name: 'Garcia',
    email: 'gadrria@gmail.com',
    city: 'Doral',
    first_name: 'Adrria',
    language: 'en',
    job_title: 'Hr Assistant',
    candidate_source: 'lensa',
    target_id: '375e3fb986124c58bbff665dfe115444',
  },
  {
    state: 'GA',
    education_level: "Master's or Ph.D",
    experience_level: 'Ten plus years',
    client_ip: '174.255.199.255',
    resume: {
      download_url:
        'https://api.lensa.com/coreg/v1/download-resume?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6ImI2ODA1YzcyMDM4ZjdmNDE1YWM5MjQ2ZDQyNTVmODc4LTI0MjUyIiwibmFtZSI6Ik1lZWsyMDIwMjAyMFJFU1VNRShkb2N4KS5kb2MiLCJ0eXBlIjoiYXBwbGljYXRpb24vdm5kLm9wZW54bWxmb3JtYXRzLW9mZmljZWRvY3VtZW50LndvcmRwcm9jZXNzaW5nbWwuZG9jdW1lbnQiLCJ2YXJpYW50Ijoib3JpZ2luYWwiLCJleHAiOjE1OTMzNTkzMjF9.tV_l-tSfBd0hIjhv_hOB__CH7hDb1lsTl8vaq23wwwg',
    },
    zip: '30303',
    desired_compensation: '$70,000',
    parsed_resume: {
      download_url:
        'https://api.lensa.com/coreg/v1/download-resume?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6ImI2ODA1YzcyMDM4ZjdmNDE1YWM5MjQ2ZDQyNTVmODc4LTI0MjUyIiwibmFtZSI6Ik1lZWsyMDIwMjAyMFJFU1VNRShkb2N4KS5kb2MueG1sIiwidHlwZSI6InRleHQveG1sIiwidmFyaWFudCI6InBhcnNlZCIsImV4cCI6MTU5MzM1OTMyMX0.JaKqWHobJ8r8YmB5iy-xUamWspt-gwPHLivTjkeJgDI',
    },
    last_name: 'Jackson',
    email: 'jacksontamiko9@gmail.com',
    city: 'Atlanta',
    first_name: 'Tamiko',
    language: 'en',
    job_title: 'Hr Supervisor',
    candidate_source: 'lensa',
    target_id: '375e3fb986124c58bbff665dfe115444',
  },
  {
    state: 'AZ',
    education_level: "Bachelor's Degree",
    experience_level: 'Ten plus years',
    client_ip: '2600:8800:5b80:6ec0:f057:56cd:554a:2e66',
    resume: {
      download_url:
        'https://api.lensa.com/coreg/v1/download-resume?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6IjUzZDE3ZmYxMTZjNWRjYmM0ZGY5NjQyZTRjNjFkMGJlLTU2NzY3IiwibmFtZSI6Im15IHJlcyAyMjQyMChkb2N4KS5kb2MiLCJ0eXBlIjoiYXBwbGljYXRpb24vdm5kLm9wZW54bWxmb3JtYXRzLW9mZmljZWRvY3VtZW50LndvcmRwcm9jZXNzaW5nbWwuZG9jdW1lbnQiLCJ2YXJpYW50Ijoib3JpZ2luYWwiLCJleHAiOjE1OTMzNTkzMjF9.9cxo8U9IPjihe3yOH_kskdEItzAwEZNkPsxGYYebwkU',
    },
    zip: '85003',
    desired_compensation: '$140,000',
    parsed_resume: {
      download_url:
        'https://api.lensa.com/coreg/v1/download-resume?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6IjUzZDE3ZmYxMTZjNWRjYmM0ZGY5NjQyZTRjNjFkMGJlLTU2NzY3IiwibmFtZSI6Im15IHJlcyAyMjQyMChkb2N4KS5kb2MueG1sIiwidHlwZSI6InRleHQveG1sIiwidmFyaWFudCI6InBhcnNlZCIsImV4cCI6MTU5MzM1OTMyMX0.bOHZe__sp4XfSz05_XinEIKJJaeUzIlKi8c0mf_bmo4',
    },
    last_name: 'Matlock ',
    email: 'davidmatlock55@gmail.com',
    city: 'Phoenix',
    first_name: 'David',
    language: 'en',
    job_title: 'Sales Manager',
    candidate_source: 'lensa',
    target_id: '375e3fb986124c58bbff665dfe115444',
  },
  {
    state: 'TX',
    education_level: "Bachelor's Degree",
    experience_level: '1-3 years',
    client_ip: '98.156.220.221',
    resume: {
      download_url:
        'https://api.lensa.com/coreg/v1/download-resume?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6IjlkZDYyZjhhYWRkMjFmMzEwMDhhYmJjMGFmMTY0ZGE2LTU4NzMwIiwibmFtZSI6IkhlcnZlUmVzdW1lMjAyMChkb2N4KS5kb2MiLCJ0eXBlIjoiYXBwbGljYXRpb24vdm5kLm9wZW54bWxmb3JtYXRzLW9mZmljZWRvY3VtZW50LndvcmRwcm9jZXNzaW5nbWwuZG9jdW1lbnQiLCJ2YXJpYW50Ijoib3JpZ2luYWwiLCJleHAiOjE1OTMzNTkzMjF9.loz-VbfRrprgElGSOa5NSrkpApNQBbCECLdEx_CeTF8',
    },
    zip: '76102',
    desired_compensation: '$65,000',
    parsed_resume: {
      download_url:
        'https://api.lensa.com/coreg/v1/download-resume?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6IjlkZDYyZjhhYWRkMjFmMzEwMDhhYmJjMGFmMTY0ZGE2LTU4NzMwIiwibmFtZSI6IkhlcnZlUmVzdW1lMjAyMChkb2N4KS5kb2MueG1sIiwidHlwZSI6InRleHQveG1sIiwidmFyaWFudCI6InBhcnNlZCIsImV4cCI6MTU5MzM1OTMyMX0.D5_ADggOOlQ1XYN1bI20aXUsKUJLixuC9ktMRqEOmK0',
    },
    last_name: 'Twala',
    email: 'hervetwa@gmail.com',
    city: 'Fort Worth',
    first_name: 'HERVE',
    language: 'en',
    job_title: 'Hr Generalist',
    candidate_source: 'lensa',
    target_id: '375e3fb986124c58bbff665dfe115444',
  },
  {
    state: 'TX',
    resume: {
      download_url:
        'https://api.lensa.com/coreg/v1/download-resume?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6ImIwYTQ4NTkyZDAzZGI3NmMxMDQ1MzcxYjIyYjExMTI5LTU0Nzg0IiwibmFtZSI6IkNvcm1hbmUgTCZEIFJlc3VtZS5kb2MiLCJ0eXBlIjoiYXBwbGljYXRpb24vbXN3b3JkIiwidmFyaWFudCI6Im9yaWdpbmFsIiwiZXhwIjoxNTkzMzU5MzIxfQ.zR_kF6I3z-Jrx-Ri6L_JqR1GiaSlBPSMuMS5nOP3Mv4',
    },
    zip: '75080',
    parsed_resume: {
      download_url:
        'https://api.lensa.com/coreg/v1/download-resume?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6ImIwYTQ4NTkyZDAzZGI3NmMxMDQ1MzcxYjIyYjExMTI5LTU0Nzg0IiwibmFtZSI6IkNvcm1hbmUgTCZEIFJlc3VtZS5kb2MueG1sIiwidHlwZSI6InRleHQveG1sIiwidmFyaWFudCI6InBhcnNlZCIsImV4cCI6MTU5MzM1OTMyMX0.GMUZua4mm0_KfSZ71X32vjfCuhBf2wNAYIN44Yv9lNs',
    },
    last_name: 'Cormane',
    email: 'mcormane@gmail.com',
    city: 'Richardson',
    first_name: 'MARIA',
    language: 'en',
    job_title: 'Hr Assistant',
    candidate_source: 'lensa',
    target_id: '375e3fb986124c58bbff665dfe115444',
  },
  {
    state: 'PA',
    education_level: "Master's or Ph.D",
    experience_level: '6-10 years',
    client_ip: '2601:46:c801:4d60:9040:401c:eff3:e03a',
    resume: {
      download_url:
        'https://api.lensa.com/coreg/v1/download-resume?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6IjNmNjc1Njg2Yjc1MTE3MjY4YmU4YWQ1ODBmMjYyMmFhLTMxNzM5IiwibmFtZSI6IkRlbmlzZSBDb29rIFJlc3VtZSAyMDIwKGRvY3gpLmRvYyIsInR5cGUiOiJhcHBsaWNhdGlvbi92bmQub3BlbnhtbGZvcm1hdHMtb2ZmaWNlZG9jdW1lbnQud29yZHByb2Nlc3NpbmdtbC5kb2N1bWVudCIsInZhcmlhbnQiOiJvcmlnaW5hbCIsImV4cCI6MTU5MzM1OTMyMX0.QKXTmQWqvyGM0q8PeNcm8o34hSu3qu2b2szg7wBHiTg',
    },
    zip: '19406',
    desired_compensation: '$75,000',
    parsed_resume: {
      download_url:
        'https://api.lensa.com/coreg/v1/download-resume?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6IjNmNjc1Njg2Yjc1MTE3MjY4YmU4YWQ1ODBmMjYyMmFhLTMxNzM5IiwibmFtZSI6IkRlbmlzZSBDb29rIFJlc3VtZSAyMDIwKGRvY3gpLmRvYy54bWwiLCJ0eXBlIjoidGV4dC94bWwiLCJ2YXJpYW50IjoicGFyc2VkIiwiZXhwIjoxNTkzMzU5MzIxfQ.BMK3lKKAKLPM9-zSuEKQIx9wgRR5IZE2XwuCt4CPNeY',
    },
    last_name: 'Cook',
    email: 'denise.cook0804@gmail.com',
    city: 'King of Prussia',
    first_name: 'Denise',
    language: 'en',
    job_title: 'Hr Generalist',
    candidate_source: 'lensa',
    target_id: '375e3fb986124c58bbff665dfe115444',
  },
  {
    state: 'DC',
    education_level: "Bachelor's Degree",
    experience_level: 'Less than 1 year',
    client_ip: '2600:1003:b864:7435:490e:72e6:f234:ddd2',
    resume: {
      download_url:
        'https://api.lensa.com/coreg/v1/download-resume?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6ImM3ZjZlNWUxNGRiOTEwZGUxZmJkZDdlZWY1MjcxNWRiLTM5NTQ2IiwibmFtZSI6Ik9mZmljaWFsIFJlc3VtZShkb2N4KS5kb2MiLCJ0eXBlIjoiYXBwbGljYXRpb24vdm5kLm9wZW54bWxmb3JtYXRzLW9mZmljZWRvY3VtZW50LndvcmRwcm9jZXNzaW5nbWwuZG9jdW1lbnQiLCJ2YXJpYW50Ijoib3JpZ2luYWwiLCJleHAiOjE1OTMzNTkzMjF9.j9ACM2WNntQTXxLtFYEIONrE6VPg4yRb7JZoG3cl1kY',
    },
    zip: '20004',
    desired_compensation: '$60,000',
    parsed_resume: {
      download_url:
        'https://api.lensa.com/coreg/v1/download-resume?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6ImM3ZjZlNWUxNGRiOTEwZGUxZmJkZDdlZWY1MjcxNWRiLTM5NTQ2IiwibmFtZSI6Ik9mZmljaWFsIFJlc3VtZShkb2N4KS5kb2MueG1sIiwidHlwZSI6InRleHQveG1sIiwidmFyaWFudCI6InBhcnNlZCIsImV4cCI6MTU5MzM1OTMyMX0.fp_S6glGLkbgCpbWEFg6AXkM4bJ2Plk7tTgSo0g2Qbc',
    },
    last_name: 'Matos Viera',
    email: 'shaquira.matos@yahoo.com',
    city: 'Washington',
    first_name: 'Ruth ',
    language: 'en',
    job_title: 'Hr Assistant',
    candidate_source: 'lensa',
    target_id: '375e3fb986124c58bbff665dfe115444',
  },
  {
    state: 'FL',
    education_level: "Master's or Ph.D",
    experience_level: '3-5 years',
    client_ip: '148.103.174.69',
    resume: {
      download_url:
        'https://api.lensa.com/coreg/v1/download-resume?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6IjQyOTQyZjIwYTRhNmE5NTYwYjNmZjJjNjVlNTYzOWQxLTk2NTE4IiwibmFtZSI6IlBhb2xhIFBhZGlsbGEgUmVzdW1lLnBkZiIsInR5cGUiOiJhcHBsaWNhdGlvbi9wZGYiLCJ2YXJpYW50Ijoib3JpZ2luYWwiLCJleHAiOjE1OTMzNTkzMjF9.ZddhMKe8lw2_8E6oFXtvLrPCD0TkEfU7K0dS7ySYGrA',
    },
    zip: '32801',
    desired_compensation: '$30,000',
    parsed_resume: {
      download_url:
        'https://api.lensa.com/coreg/v1/download-resume?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6IjQyOTQyZjIwYTRhNmE5NTYwYjNmZjJjNjVlNTYzOWQxLTk2NTE4IiwibmFtZSI6IlBhb2xhIFBhZGlsbGEgUmVzdW1lLnBkZi54bWwiLCJ0eXBlIjoidGV4dC94bWwiLCJ2YXJpYW50IjoicGFyc2VkIiwiZXhwIjoxNTkzMzU5MzIxfQ.ZyfyI3oKXYqLMY_jiV28RfwCxecGWYanyxmUATbiqZ8',
    },
    last_name: 'Padilla',
    email: 'paopadilla@outlook.com',
    city: 'Orlando',
    first_name: 'Paola',
    language: 'en',
    job_title: 'Hr',
    candidate_source: 'lensa',
    target_id: '375e3fb986124c58bbff665dfe115444',
  },
  {
    state: 'MI',
    education_level: "Bachelor's Degree",
    experience_level: '6-10 years',
    client_ip: '67.149.37.69',
    resume: {
      download_url:
        'https://api.lensa.com/coreg/v1/download-resume?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6IjBlOGNjMmY3YzcyZDRjZjBhMzk1MGYxMmY5MTFiZjAzLTU0MTMyIiwibmFtZSI6IkRhbGFsIE5haGxlLUF5b3ViIFJlc3VtZSBKdW5lIDIwMjAoZG9jeCkuZG9jIiwidHlwZSI6ImFwcGxpY2F0aW9uL3ZuZC5vcGVueG1sZm9ybWF0cy1vZmZpY2Vkb2N1bWVudC53b3JkcHJvY2Vzc2luZ21sLmRvY3VtZW50IiwidmFyaWFudCI6Im9yaWdpbmFsIiwiZXhwIjoxNTkzMzU5MzIxfQ.jZMdtGqU5VdyA7mkk9P8yyvc-JmDeoCkcPIppRz-xmg',
    },
    zip: '48226',
    desired_compensation: '$50,000',
    parsed_resume: {
      download_url:
        'https://api.lensa.com/coreg/v1/download-resume?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6IjBlOGNjMmY3YzcyZDRjZjBhMzk1MGYxMmY5MTFiZjAzLTU0MTMyIiwibmFtZSI6IkRhbGFsIE5haGxlLUF5b3ViIFJlc3VtZSBKdW5lIDIwMjAoZG9jeCkuZG9jLnhtbCIsInR5cGUiOiJ0ZXh0L3htbCIsInZhcmlhbnQiOiJwYXJzZWQiLCJleHAiOjE1OTMzNTkzMjF9.dMK9IQR4g2Fy63lNNyV3A2euSErw4tHBdyOWBzcO3lo',
    },
    last_name: 'Nahle-Ayoub',
    email: 'ddnahle@gmail.com',
    city: 'Detroit',
    first_name: 'Dalal',
    language: 'en',
    job_title: 'Hr',
    candidate_source: 'lensa',
    target_id: '375e3fb986124c58bbff665dfe115444',
  },
  {
    state: 'MI',
    education_level: "Bachelor's Degree",
    experience_level: 'Ten plus years',
    client_ip: '2607:fb90:8944:87e9:3dd0:f84b:365a:1ff4',
    resume: {
      download_url:
        'https://api.lensa.com/coreg/v1/download-resume?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6IjVlZWU1MDdkODdhZGYzYWJhN2M4ZDQ3OTZkNzYwM2E3LTEyMjQ2OSIsIm5hbWUiOiJLYXJsU3RlaW4yMDIwLnBkZiIsInR5cGUiOiJhcHBsaWNhdGlvbi9wZGYiLCJ2YXJpYW50Ijoib3JpZ2luYWwiLCJleHAiOjE1OTMzNTkzMjF9.ojp49eL2kxfRC_J9GKqCvko-ZUkJPg9C2LglNOuFo_c',
    },
    zip: '48226',
    desired_compensation: '$100,000',
    parsed_resume: {
      download_url:
        'https://api.lensa.com/coreg/v1/download-resume?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6IjVlZWU1MDdkODdhZGYzYWJhN2M4ZDQ3OTZkNzYwM2E3LTEyMjQ2OSIsIm5hbWUiOiJLYXJsU3RlaW4yMDIwLnBkZi54bWwiLCJ0eXBlIjoidGV4dC94bWwiLCJ2YXJpYW50IjoicGFyc2VkIiwiZXhwIjoxNTkzMzU5MzIxfQ.GhoideabVGQT0j10RNSRMMuaOhN3VSqgjXRTIJFqAIE',
    },
    last_name: 'Stein',
    email: 'karlstein527@gmail.com',
    city: 'Detroit',
    first_name: 'Karl',
    language: 'en',
    job_title: 'Regional Business Development Manager',
    candidate_source: 'lensa',
    target_id: '375e3fb986124c58bbff665dfe115444',
  },
  {
    state: 'VA',
    education_level: "Bachelor's Degree",
    experience_level: 'Ten plus years',
    client_ip: '2001:579:c00c:4a:21c2:9ba9:961f:671f',
    resume: {
      download_url:
        'https://api.lensa.com/coreg/v1/download-resume?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6Ijk0MGM5MmI3NDc0MWIzNjFmZDNhMzJhZjQ5ODczMjVkLTgxOTUyIiwibmFtZSI6IlJlc3VtZSAgLSBSb3NlbWFyeSBCb3lkIDUucGRmIiwidHlwZSI6ImFwcGxpY2F0aW9uL3BkZiIsInZhcmlhbnQiOiJvcmlnaW5hbCIsImV4cCI6MTU5MzM1OTMyMX0.YLVAZJEuk5ULin7Wr5Hlal3qaCFVjMrJ0kK-VVuZNRw',
    },
    zip: '23510',
    desired_compensation: '$50,000',
    parsed_resume: {
      download_url:
        'https://api.lensa.com/coreg/v1/download-resume?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6Ijk0MGM5MmI3NDc0MWIzNjFmZDNhMzJhZjQ5ODczMjVkLTgxOTUyIiwibmFtZSI6IlJlc3VtZSAgLSBSb3NlbWFyeSBCb3lkIDUucGRmLnhtbCIsInR5cGUiOiJ0ZXh0L3htbCIsInZhcmlhbnQiOiJwYXJzZWQiLCJleHAiOjE1OTMzNTkzMjF9.0Vc3YACM3fPjXsb8xxxw2ei4R-DEwTcoU6F0jR7kNq0',
    },
    last_name: 'Boyd',
    email: 'roebear57@aol.com',
    city: 'Norfolk',
    first_name: 'Rosemary',
    language: 'en',
    job_title: 'Hr',
    candidate_source: 'lensa',
    target_id: '375e3fb986124c58bbff665dfe115444',
  },
  {
    state: 'TX',
    education_level: 'Some College',
    experience_level: 'Ten plus years',
    client_ip: '2600:1700:214:e410:95c:fe9d:af8a:1aff',
    resume: {
      download_url:
        'https://api.lensa.com/coreg/v1/download-resume?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6IjA0NjA3NjkxZTQ3ZjcyZGY5MDNjODBkY2VjNmM0MjgwLTM4ODc4IiwibmFtZSI6IlBhdHJpY2sgU3VsbGl2YW4gUmVzdW1lKGRvY3gpLmRvYyIsInR5cGUiOiJhcHBsaWNhdGlvbi92bmQub3BlbnhtbGZvcm1hdHMtb2ZmaWNlZG9jdW1lbnQud29yZHByb2Nlc3NpbmdtbC5kb2N1bWVudCIsInZhcmlhbnQiOiJvcmlnaW5hbCIsImV4cCI6MTU5MzM1OTMyMX0.slnhgAp54QFG6ekL09A6TXHlS_ebDqhMZ8cLfI3_4Ko',
    },
    zip: '78701',
    desired_compensation: '$50,000',
    parsed_resume: {
      download_url:
        'https://api.lensa.com/coreg/v1/download-resume?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6IjA0NjA3NjkxZTQ3ZjcyZGY5MDNjODBkY2VjNmM0MjgwLTM4ODc4IiwibmFtZSI6IlBhdHJpY2sgU3VsbGl2YW4gUmVzdW1lKGRvY3gpLmRvYy54bWwiLCJ0eXBlIjoidGV4dC94bWwiLCJ2YXJpYW50IjoicGFyc2VkIiwiZXhwIjoxNTkzMzU5MzIxfQ.pqk8-CeT2Z1I8yx8GwY4hBGwr9rqdHOgC41iDzzD6Fw',
    },
    last_name: 'Sullivan',
    email: 'patsull67@aol.com',
    city: 'Austin',
    first_name: 'Patrick',
    language: 'en',
    job_title: 'Regional Business Development Manager',
    candidate_source: 'lensa',
    target_id: '375e3fb986124c58bbff665dfe115444',
  },
  {
    state: 'VA',
    education_level: "Master's or Ph.D",
    experience_level: 'Less than 1 year',
    client_ip: '70.183.4.54',
    resume: {
      download_url:
        'https://api.lensa.com/coreg/v1/download-resume?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6IjUzNjgwOTYyZjFhOTFlMjIxOTMyYzAyZDFkYjQzZTUzLTUyMTk5IiwibmFtZSI6IlJlc3VtZVRoaXBwcmFwYSAtIEdvb2dsZSBEb2NzLnBkZiIsInR5cGUiOiJhcHBsaWNhdGlvbi9wZGYiLCJ2YXJpYW50Ijoib3JpZ2luYWwiLCJleHAiOjE1OTMzNTkzMjF9.obr-Y8etJOSJLw9qb9sgG7TQeTurkwz-fgddrJE5vU4',
    },
    zip: '22030',
    desired_compensation: '$70,000',
    parsed_resume: {
      download_url:
        'https://api.lensa.com/coreg/v1/download-resume?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6IjUzNjgwOTYyZjFhOTFlMjIxOTMyYzAyZDFkYjQzZTUzLTUyMTk5IiwibmFtZSI6IlJlc3VtZVRoaXBwcmFwYSAtIEdvb2dsZSBEb2NzLnBkZi54bWwiLCJ0eXBlIjoidGV4dC94bWwiLCJ2YXJpYW50IjoicGFyc2VkIiwiZXhwIjoxNTkzMzU5MzIxfQ.o5QdkVmHQl6_6sPBKplMT60sl2AnkwBeyXWweYe-CFY',
    },
    last_name: 'Popiyatrakul ',
    email: 'noon62@gmail.com',
    city: 'Fairfax',
    first_name: 'Thipprapa ',
    language: 'en',
    job_title: 'Junior Software Developer',
    candidate_source: 'lensa',
    target_id: '375e3fb986124c58bbff665dfe115444',
  },
  {
    state: 'IL',
    education_level: "Master's or Ph.D",
    experience_level: 'Ten plus years',
    client_ip: '115.98.58.45',
    resume: {
      download_url:
        'https://api.lensa.com/coreg/v1/download-resume?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6IjQ2YzBhYWI2ODYzNjIwZmI0ZDUzMTU0Mzk0ZTdkODk4LTkxNjQ4IiwibmFtZSI6IlN1ZGhhIF9RQV9SZXN1bWUgLmRvYyIsInR5cGUiOiJhcHBsaWNhdGlvbi9tc3dvcmQiLCJ2YXJpYW50Ijoib3JpZ2luYWwiLCJleHAiOjE1OTMzNTkzMjF9.F8k6E7cYO1QaZtY6O415GbSyV52Y6PfCqIT2G_soSrw',
    },
    zip: '60602',
    desired_compensation: '$65,000',
    parsed_resume: {
      download_url:
        'https://api.lensa.com/coreg/v1/download-resume?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6IjQ2YzBhYWI2ODYzNjIwZmI0ZDUzMTU0Mzk0ZTdkODk4LTkxNjQ4IiwibmFtZSI6IlN1ZGhhIF9RQV9SZXN1bWUgLmRvYy54bWwiLCJ0eXBlIjoidGV4dC94bWwiLCJ2YXJpYW50IjoicGFyc2VkIiwiZXhwIjoxNTkzMzU5MzIxfQ.sigchynkQKA-Cul7NSlajkQKtAFVys5fx1T1PP2GwO4',
    },
    last_name: 'Burugupalli',
    email: 'susheel@windycitytechnologies.com',
    city: 'Chicago',
    first_name: 'Venkata',
    language: 'en',
    job_title: 'SQA Engineer',
    candidate_source: 'lensa',
    target_id: '375e3fb986124c58bbff665dfe115444',
  },
  {
    state: 'NJ',
    education_level: "Bachelor's Degree",
    experience_level: 'Less than 1 year',
    client_ip: '2601:86:600:28a0:98af:b708:8808:8d1d',
    resume: {
      download_url:
        'https://api.lensa.com/coreg/v1/download-resume?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6IjQwODllNWY3ZWQ5MWNmYTc1MzVhNGIzNWQzNjYzZmRkLTUzNDA1IiwibmFtZSI6IiBEYW5hIFRvY2VsIE9mZmljaWFsIFJlc3VtZS4gLmRvY3gucGRmIiwidHlwZSI6ImFwcGxpY2F0aW9uL3BkZiIsInZhcmlhbnQiOiJvcmlnaW5hbCIsImV4cCI6MTU5MzM1OTMyMX0.JyF_m8I-hLRTzIt1w8pdf3I5cLtUtWDIFRWbgjxeCb4',
    },
    zip: '07102',
    desired_compensation: '$25,000',
    parsed_resume: {
      download_url:
        'https://api.lensa.com/coreg/v1/download-resume?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6IjQwODllNWY3ZWQ5MWNmYTc1MzVhNGIzNWQzNjYzZmRkLTUzNDA1IiwibmFtZSI6IiBEYW5hIFRvY2VsIE9mZmljaWFsIFJlc3VtZS4gLmRvY3gucGRmLnhtbCIsInR5cGUiOiJ0ZXh0L3htbCIsInZhcmlhbnQiOiJwYXJzZWQiLCJleHAiOjE1OTMzNTkzMjF9.tIh3qqVJbzxZqHQ6dqj3DUyH3o8m7J2cRC1KA8_SoH4',
    },
    last_name: 'Tocel',
    email: 'toceld1@tcnj.edu',
    city: 'Newark',
    first_name: 'Dana ',
    language: 'en',
    job_title: 'Hr Analyst',
    candidate_source: 'lensa',
    target_id: '375e3fb986124c58bbff665dfe115444',
  },
  {
    state: 'MA',
    education_level: "Bachelor's Degree",
    experience_level: 'Ten plus years',
    client_ip: '74.104.140.145',
    resume: {
      download_url:
        'https://api.lensa.com/coreg/v1/download-resume?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6IjdkNTdkZDBmMzAxNjI2Nzg0NmM4ZDk0MDI2NjcxOTA3LTM2NDU0IiwibmFtZSI6IkRhdmlkIEthdHogcmVzdW1lIEp1bmUgMjAyMChkb2N4KS5kb2MiLCJ0eXBlIjoiYXBwbGljYXRpb24vdm5kLm9wZW54bWxmb3JtYXRzLW9mZmljZWRvY3VtZW50LndvcmRwcm9jZXNzaW5nbWwuZG9jdW1lbnQiLCJ2YXJpYW50Ijoib3JpZ2luYWwiLCJleHAiOjE1OTMzNTkzMjF9.i0jBrkZZCnBODZF3spyWdbiMgJBEu9VgAve2mNRBQ5k',
    },
    zip: '02109',
    desired_compensation: '$225,000',
    parsed_resume: {
      download_url:
        'https://api.lensa.com/coreg/v1/download-resume?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6IjdkNTdkZDBmMzAxNjI2Nzg0NmM4ZDk0MDI2NjcxOTA3LTM2NDU0IiwibmFtZSI6IkRhdmlkIEthdHogcmVzdW1lIEp1bmUgMjAyMChkb2N4KS5kb2MueG1sIiwidHlwZSI6InRleHQveG1sIiwidmFyaWFudCI6InBhcnNlZCIsImV4cCI6MTU5MzM1OTMyMX0.VEnnun0osSLnxAAxxrvbHWb_dttJkAvUdiFh3xBx-PI',
    },
    last_name: 'Katz',
    email: 'dave_s20@hotmail.com',
    city: 'Boston',
    first_name: 'Dave',
    language: 'en',
    job_title: 'Sales Account Manager',
    candidate_source: 'lensa',
    target_id: '375e3fb986124c58bbff665dfe115444',
  },
  {
    state: 'MI',
    education_level: "Bachelor's Degree",
    experience_level: '6-10 years',
    client_ip: '2602:304:cd8d:6760:7da5:596c:9c3e:b0a',
    resume: {
      download_url:
        'https://api.lensa.com/coreg/v1/download-resume?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6IjFiNGZjZTI4YjYwYTZkNTE4MzkyZmY0YTM0ZTNjZmM0LTEyODgzIiwibmFtZSI6IkpMIFJlc3VtZSAyMDE5KGRvY3gpLmRvYyIsInR5cGUiOiJhcHBsaWNhdGlvbi92bmQub3BlbnhtbGZvcm1hdHMtb2ZmaWNlZG9jdW1lbnQud29yZHByb2Nlc3NpbmdtbC5kb2N1bWVudCIsInZhcmlhbnQiOiJvcmlnaW5hbCIsImV4cCI6MTU5MzM1OTMyMX0.HAsMlq6GgN6onsVNKApGZh0HgqALHjJzBK2Z0PH2bFY',
    },
    zip: '48375',
    desired_compensation: '$60,000',
    parsed_resume: {
      download_url:
        'https://api.lensa.com/coreg/v1/download-resume?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6IjFiNGZjZTI4YjYwYTZkNTE4MzkyZmY0YTM0ZTNjZmM0LTEyODgzIiwibmFtZSI6IkpMIFJlc3VtZSAyMDE5KGRvY3gpLmRvYy54bWwiLCJ0eXBlIjoidGV4dC94bWwiLCJ2YXJpYW50IjoicGFyc2VkIiwiZXhwIjoxNTkzMzU5MzIxfQ.kEFbQ3z4R51EPFkpR4f8vMEnUMwCFuRjmEZSkBfIoyI',
    },
    last_name: 'Laskowski',
    email: 'laskowskijennifer@gmail.com',
    city: 'Novi',
    first_name: 'Jennifer ',
    language: 'en',
    job_title: 'Hr Generalist',
    candidate_source: 'lensa',
    target_id: '375e3fb986124c58bbff665dfe115444',
  },
  {
    state: 'NM',
    education_level: "Master's or Ph.D",
    experience_level: 'Ten plus years',
    client_ip: '2601:8c3:c200:4170:d889:f42:6f7d:4071',
    resume: {
      download_url:
        'https://api.lensa.com/coreg/v1/download-resume?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6ImFkY2E2Y2IxZmI4NjU2ZTRkZmNkNDA2ZDJkZDkxZmM0LTQ1MDE0IiwibmFtZSI6IlJlc3VtZUhSIE1nbXQwNjIzMjAoZG9jeCkuZG9jIiwidHlwZSI6ImFwcGxpY2F0aW9uL3ZuZC5vcGVueG1sZm9ybWF0cy1vZmZpY2Vkb2N1bWVudC53b3JkcHJvY2Vzc2luZ21sLmRvY3VtZW50IiwidmFyaWFudCI6Im9yaWdpbmFsIiwiZXhwIjoxNTkzMzU5MzIxfQ.2PDhTaAaajZ75a2zyFniX2eQ75aKB1IXcpY7s9nF9U4',
    },
    zip: '87102',
    desired_compensation: '$90,000',
    parsed_resume: {
      download_url:
        'https://api.lensa.com/coreg/v1/download-resume?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6ImFkY2E2Y2IxZmI4NjU2ZTRkZmNkNDA2ZDJkZDkxZmM0LTQ1MDE0IiwibmFtZSI6IlJlc3VtZUhSIE1nbXQwNjIzMjAoZG9jeCkuZG9jLnhtbCIsInR5cGUiOiJ0ZXh0L3htbCIsInZhcmlhbnQiOiJwYXJzZWQiLCJleHAiOjE1OTMzNTkzMjF9.EpBjEtDBkUcbfR7F-FTTV0JDfJPNoGw3hhBp3rKcEoA',
    },
    last_name: 'Vildasol',
    email: 'nmcup@yahoo.com',
    city: 'Albuquerque',
    first_name: 'Manuel',
    language: 'en',
    job_title: 'Hr Manager',
    candidate_source: 'lensa',
    target_id: '375e3fb986124c58bbff665dfe115444',
  },
  {
    state: 'MI',
    education_level: "Bachelor's Degree",
    experience_level: 'Ten plus years',
    client_ip: '2600:1700:9860:ab60:7cff:694a:a70:4beb',
    resume: {
      download_url:
        'https://api.lensa.com/coreg/v1/download-resume?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6IjQyYTVkODEwZDFmNzRkOTc2NGRiOWFiN2E1YmY1NTRlLTI5OTU5IiwibmFtZSI6IlJvbm5pZUhhZ2VsX3Jlc3VtZShkb2N4KS5kb2MiLCJ0eXBlIjoiYXBwbGljYXRpb24vdm5kLm9wZW54bWxmb3JtYXRzLW9mZmljZWRvY3VtZW50LndvcmRwcm9jZXNzaW5nbWwuZG9jdW1lbnQiLCJ2YXJpYW50Ijoib3JpZ2luYWwiLCJleHAiOjE1OTMzNTkzMjF9.Q2tX1VYJYd1KeJZyXq3MJKyDEvVTUsr-aF_qZxgYk3Y',
    },
    zip: '48226',
    desired_compensation: '$110,000',
    parsed_resume: {
      download_url:
        'https://api.lensa.com/coreg/v1/download-resume?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6IjQyYTVkODEwZDFmNzRkOTc2NGRiOWFiN2E1YmY1NTRlLTI5OTU5IiwibmFtZSI6IlJvbm5pZUhhZ2VsX3Jlc3VtZShkb2N4KS5kb2MueG1sIiwidHlwZSI6InRleHQveG1sIiwidmFyaWFudCI6InBhcnNlZCIsImV4cCI6MTU5MzM1OTMyMX0.NxEVG1M7G-TUk9j2-j8YM6RniBJ5NKW6HT1tRSQwaU0',
    },
    last_name: 'Hagel',
    email: 'ronhagel@msn.com',
    city: 'Detroit',
    first_name: 'Ronnie',
    language: 'en',
    job_title: 'Hr Manager',
    candidate_source: 'lensa',
    target_id: '375e3fb986124c58bbff665dfe115444',
  },
  {
    state: 'VA',
    education_level: "Master's or Ph.D",
    experience_level: 'Ten plus years',
    client_ip: '96.231.22.155',
    resume: {
      download_url:
        'https://api.lensa.com/coreg/v1/download-resume?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6IjI2MWM1ZWU5ZGIwN2U4MjcyMGMyYjkzODRhOTdhY2QyLTQ0NzM4IiwibmFtZSI6IlJlc3VtZS0yMC1hcmMoZG9jeCkuZG9jIiwidHlwZSI6ImFwcGxpY2F0aW9uL3ZuZC5vcGVueG1sZm9ybWF0cy1vZmZpY2Vkb2N1bWVudC53b3JkcHJvY2Vzc2luZ21sLmRvY3VtZW50IiwidmFyaWFudCI6Im9yaWdpbmFsIiwiZXhwIjoxNTkzMzU5MzIxfQ._wJbpzPy4_ofEmgxRqOeBk-HPowFInxIhnRST9f-pSY',
    },
    zip: '20151',
    desired_compensation: '$150,000',
    parsed_resume: {
      download_url:
        'https://api.lensa.com/coreg/v1/download-resume?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6IjI2MWM1ZWU5ZGIwN2U4MjcyMGMyYjkzODRhOTdhY2QyLTQ0NzM4IiwibmFtZSI6IlJlc3VtZS0yMC1hcmMoZG9jeCkuZG9jLnhtbCIsInR5cGUiOiJ0ZXh0L3htbCIsInZhcmlhbnQiOiJwYXJzZWQiLCJleHAiOjE1OTMzNTkzMjF9.r17M8ghJjP0JYwkKI_-sYOm4iPAK9LM7M1gfSJgWRWM',
    },
    last_name: 'Sun',
    email: 'billwenmingsun@gmail.com',
    city: 'Chantilly',
    first_name: 'Bill',
    language: 'en',
    job_title: 'Senior Software Architect',
    candidate_source: 'lensa',
    target_id: '375e3fb986124c58bbff665dfe115444',
  },
  {
    state: 'NY',
    education_level: "Master's or Ph.D",
    experience_level: 'Ten plus years',
    client_ip: '74.66.194.253',
    resume: {
      download_url:
        'https://api.lensa.com/coreg/v1/download-resume?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6IjI2OWY1YTk0NzA2MTA5MDNmZmFlOGZjZWU5NWVkZTYxLTI3Mjk2NyIsIm5hbWUiOiJCSUFOQ0EgQkFIQVJZIFJFU1VNRSAyMDIwLnBkZiIsInR5cGUiOiJhcHBsaWNhdGlvbi9wZGYiLCJ2YXJpYW50Ijoib3JpZ2luYWwiLCJleHAiOjE1OTMzNTkzMjF9.0XMgSZMwC_XwGYRcr6IdM1HrFIU1CL0_JSRbbGBQ-Pg',
    },
    zip: '10007',
    desired_compensation: '$80,000',
    parsed_resume: {
      download_url:
        'https://api.lensa.com/coreg/v1/download-resume?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6IjI2OWY1YTk0NzA2MTA5MDNmZmFlOGZjZWU5NWVkZTYxLTI3Mjk2NyIsIm5hbWUiOiJCSUFOQ0EgQkFIQVJZIFJFU1VNRSAyMDIwLnBkZi54bWwiLCJ0eXBlIjoidGV4dC94bWwiLCJ2YXJpYW50IjoicGFyc2VkIiwiZXhwIjoxNTkzMzU5MzIxfQ.tT__0xj2dJsj-6U1yqEGJf0FaMONhY-es02Ty9-QqqU',
    },
    last_name: 'Bahary',
    email: 'baharybianca@aol.com',
    city: 'New York',
    first_name: 'Bianca',
    language: 'en',
    job_title: 'Corporate Communications Manager',
    candidate_source: 'lensa',
    target_id: '375e3fb986124c58bbff665dfe115444',
  },
  {
    state: 'OH',
    education_level: "Bachelor's Degree",
    experience_level: 'Ten plus years',
    client_ip: '107.143.66.161',
    resume: {
      download_url:
        'https://api.lensa.com/coreg/v1/download-resume?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6IjNhMWY4MjYzNWYzODk3YmY3MzIxODM4MDYzZmIzY2NmLTI5MDU3IiwibmFtZSI6IlJlYmVjYSBNYXJzaCBSZXZpc2VkIFJlc3VtZSAwNTE5MjAyMChkb2N4KS5kb2MiLCJ0eXBlIjoiYXBwbGljYXRpb24vdm5kLm9wZW54bWxmb3JtYXRzLW9mZmljZWRvY3VtZW50LndvcmRwcm9jZXNzaW5nbWwuZG9jdW1lbnQiLCJ2YXJpYW50Ijoib3JpZ2luYWwiLCJleHAiOjE1OTMzNTkzMjF9.E4qIEhR5iaSyTFEPAHLd65nnuchE6CbOayvOc60FeU0',
    },
    zip: '43215',
    desired_compensation: '$80,000',
    parsed_resume: {
      download_url:
        'https://api.lensa.com/coreg/v1/download-resume?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6IjNhMWY4MjYzNWYzODk3YmY3MzIxODM4MDYzZmIzY2NmLTI5MDU3IiwibmFtZSI6IlJlYmVjYSBNYXJzaCBSZXZpc2VkIFJlc3VtZSAwNTE5MjAyMChkb2N4KS5kb2MueG1sIiwidHlwZSI6InRleHQveG1sIiwidmFyaWFudCI6InBhcnNlZCIsImV4cCI6MTU5MzM1OTMyMX0.dd5oPGDG7hdrV3UD_pMwGhvZZ4dypayYj9esAvLd9Js',
    },
    last_name: 'Marsh ',
    email: 'rbccancel@yahoo.com',
    city: 'Columbus',
    first_name: 'Rebeca ',
    language: 'en',
    job_title: 'Hr',
    candidate_source: 'lensa',
    target_id: '375e3fb986124c58bbff665dfe115444',
  },
  {
    state: 'NC',
    education_level: "Master's or Ph.D",
    experience_level: '6-10 years',
    client_ip: '208.104.51.212',
    resume: {
      download_url:
        'https://api.lensa.com/coreg/v1/download-resume?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6ImRkZWE1MWY1ZDczMTg4MGFmNjM3MTAxM2Y3NTZkMWIwLTE4ODk2OSIsIm5hbWUiOiJLcmlzaG5hX05hbmRhX1Jlc3VtZS5wZGYiLCJ0eXBlIjoiYXBwbGljYXRpb24vcGRmIiwidmFyaWFudCI6Im9yaWdpbmFsIiwiZXhwIjoxNTkzMzU5MzIxfQ.D4UwDIQpnIPl8uepJ6Hua5hkNwf-LQTO_B3RG921kDI',
    },
    zip: '28202',
    desired_compensation: '$80,000',
    parsed_resume: {
      download_url:
        'https://api.lensa.com/coreg/v1/download-resume?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6ImRkZWE1MWY1ZDczMTg4MGFmNjM3MTAxM2Y3NTZkMWIwLTE4ODk2OSIsIm5hbWUiOiJLcmlzaG5hX05hbmRhX1Jlc3VtZS5wZGYueG1sIiwidHlwZSI6InRleHQveG1sIiwidmFyaWFudCI6InBhcnNlZCIsImV4cCI6MTU5MzM1OTMyMX0.J4BfsEqea96Vj7vLcRBeUyNK3Vp45uhbT51Wse-40Qk',
    },
    last_name: 'NANDA',
    email: 'krisnainfo@gmail.com',
    city: 'Charlotte',
    first_name: 'KRISHNA',
    language: 'en',
    job_title: 'Hr',
    candidate_source: 'lensa',
    target_id: '375e3fb986124c58bbff665dfe115444',
  },
  {
    state: 'MI',
    education_level: "Bachelor's Degree",
    experience_level: 'Ten plus years',
    client_ip: '76.255.215.84',
    resume: {
      download_url:
        'https://api.lensa.com/coreg/v1/download-resume?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6IjlmOTNhNjdhMmY4MWM1OTk2OTAxMzkwZTNmZWQyYWQ0LTE2MzEwMCIsIm5hbWUiOiJSZXN1bWUgKEJyaWFuIEp1bmcpLnBkZiIsInR5cGUiOiJhcHBsaWNhdGlvbi9wZGYiLCJ2YXJpYW50Ijoib3JpZ2luYWwiLCJleHAiOjE1OTMzNTkzMjF9.J_Nx8noVc_I80QxvQL5_-j4olQ0iWTUV7caojuw6vA4',
    },
    zip: '48076',
    desired_compensation: '$90,000',
    parsed_resume: {
      download_url:
        'https://api.lensa.com/coreg/v1/download-resume?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6IjlmOTNhNjdhMmY4MWM1OTk2OTAxMzkwZTNmZWQyYWQ0LTE2MzEwMCIsIm5hbWUiOiJSZXN1bWUgKEJyaWFuIEp1bmcpLnBkZi54bWwiLCJ0eXBlIjoidGV4dC94bWwiLCJ2YXJpYW50IjoicGFyc2VkIiwiZXhwIjoxNTkzMzU5MzIxfQ._HEKrA40PrA-pMWbuBfx8x_OCNFUeguIOUItR01KYwI',
    },
    last_name: 'Jung',
    email: 'bgjung123@gmail.com',
    city: 'Southfield',
    first_name: 'Brian',
    language: 'en',
    job_title: 'Sales Account Manager',
    candidate_source: 'lensa',
    target_id: '375e3fb986124c58bbff665dfe115444',
  },
  {
    state: 'FL',
    education_level: "Master's or Ph.D",
    experience_level: 'Ten plus years',
    client_ip: '2607:fb90:e440:4e84:3598:54c6:eb55:5381',
    resume: {
      download_url:
        'https://api.lensa.com/coreg/v1/download-resume?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6Ijk5NjA4YmEzNDJlZTMxNGRmODljYWU2Zjg4Nzc5Y2ZhLTI1NDQ0IiwibmFtZSI6IkNIQVNNSU5FIEhBTUlMVE9OX1Jlc3VtZV8oZG9jeCkuZG9jIiwidHlwZSI6ImFwcGxpY2F0aW9uL3ZuZC5vcGVueG1sZm9ybWF0cy1vZmZpY2Vkb2N1bWVudC53b3JkcHJvY2Vzc2luZ21sLmRvY3VtZW50IiwidmFyaWFudCI6Im9yaWdpbmFsIiwiZXhwIjoxNTkzMzU5MzIxfQ.qJINl2_0jVCxBgN3seK05HhR4zScGZPyXAdIjwMbYx8',
    },
    zip: '33602',
    desired_compensation: '$130,000',
    parsed_resume: {
      download_url:
        'https://api.lensa.com/coreg/v1/download-resume?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6Ijk5NjA4YmEzNDJlZTMxNGRmODljYWU2Zjg4Nzc5Y2ZhLTI1NDQ0IiwibmFtZSI6IkNIQVNNSU5FIEhBTUlMVE9OX1Jlc3VtZV8oZG9jeCkuZG9jLnhtbCIsInR5cGUiOiJ0ZXh0L3htbCIsInZhcmlhbnQiOiJwYXJzZWQiLCJleHAiOjE1OTMzNTkzMjF9.UEGfE_41PZ8Qf7UETVzZn9gI9lx-de1ec2YcjpJiPNQ',
    },
    last_name: '',
    email: 'chazjones02@gmail.com',
    city: 'Tampa',
    first_name: '',
    language: 'en',
    job_title: 'Talent Acquisition Manager',
    candidate_source: 'lensa',
    target_id: '375e3fb986124c58bbff665dfe115444',
  },
  {
    state: 'FL',
    education_level: "Bachelor's Degree",
    experience_level: '6-10 years',
    client_ip: '2603:9000:e702:bb9e:297f:7f60:ef72:4bc2',
    resume: {
      download_url:
        'https://api.lensa.com/coreg/v1/download-resume?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6IjdlMzA4YWYyNDE3ZDY3YmM3YjM5NDkwYzhlOTgyYzAyLTI2NzU4IiwibmFtZSI6IlphY2hhcnkgQW5nZWwgUmVzdW1lKGRvY3gpLmRvYyIsInR5cGUiOiJhcHBsaWNhdGlvbi92bmQub3BlbnhtbGZvcm1hdHMtb2ZmaWNlZG9jdW1lbnQud29yZHByb2Nlc3NpbmdtbC5kb2N1bWVudCIsInZhcmlhbnQiOiJvcmlnaW5hbCIsImV4cCI6MTU5MzM1OTMyMX0.zPbyARNRGzzQ3x4Jx3GAofdjSJkOvynl1McFAODzJ7A',
    },
    zip: '33602',
    desired_compensation: '$70,000',
    parsed_resume: {
      download_url:
        'https://api.lensa.com/coreg/v1/download-resume?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6IjdlMzA4YWYyNDE3ZDY3YmM3YjM5NDkwYzhlOTgyYzAyLTI2NzU4IiwibmFtZSI6IlphY2hhcnkgQW5nZWwgUmVzdW1lKGRvY3gpLmRvYy54bWwiLCJ0eXBlIjoidGV4dC94bWwiLCJ2YXJpYW50IjoicGFyc2VkIiwiZXhwIjoxNTkzMzU5MzIxfQ.nGIUoOTs2F5i_s-LCzzfCh0NUT6cZ5XjFK3kgIhblAo',
    },
    last_name: 'Angel',
    email: 'zacharyangel60@gmail.com',
    city: 'Tampa',
    first_name: 'Zachary',
    language: 'en',
    job_title: 'Regional Sales Manager',
    candidate_source: 'lensa',
    target_id: '375e3fb986124c58bbff665dfe115444',
  },
  {
    state: 'CO',
    education_level: "Master's or Ph.D",
    experience_level: '3-5 years',
    client_ip: '2601:282:1300:2c60:59f2:19a9:97c9:8341',
    resume: {
      download_url:
        'https://api.lensa.com/coreg/v1/download-resume?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6ImExN2NiNGEwYzdmZjIyZjI4MzdjZTQ2MmJkZWIxNGE5LTE2NjkzIiwibmFtZSI6InVwZGF0ZWQgcmVzdW1lIDIwMjAoZG9jeCkuZG9jIiwidHlwZSI6ImFwcGxpY2F0aW9uL3ZuZC5vcGVueG1sZm9ybWF0cy1vZmZpY2Vkb2N1bWVudC53b3JkcHJvY2Vzc2luZ21sLmRvY3VtZW50IiwidmFyaWFudCI6Im9yaWdpbmFsIiwiZXhwIjoxNTkzMzU5MzIxfQ.Q2sCqa0qMo8P0ZjcwhVEkC0KesWNmNa1OiELxvGvGlI',
    },
    zip: '80012',
    desired_compensation: '$55,000',
    parsed_resume: {
      download_url:
        'https://api.lensa.com/coreg/v1/download-resume?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6ImExN2NiNGEwYzdmZjIyZjI4MzdjZTQ2MmJkZWIxNGE5LTE2NjkzIiwibmFtZSI6InVwZGF0ZWQgcmVzdW1lIDIwMjAoZG9jeCkuZG9jLnhtbCIsInR5cGUiOiJ0ZXh0L3htbCIsInZhcmlhbnQiOiJwYXJzZWQiLCJleHAiOjE1OTMzNTkzMjF9.MAkYlpNSnA5rEEdmiBJrUl72YZH5ABR4Kz9tUOzaEOE',
    },
    last_name: 'Hassan',
    email: 'amizfeline@yahoo.com',
    city: 'Aurora',
    first_name: 'Atanya',
    language: 'en',
    job_title: 'Hr Generalist',
    candidate_source: 'lensa',
    target_id: '375e3fb986124c58bbff665dfe115444',
  },
  {
    state: 'KS',
    education_level: "Bachelor's Degree",
    experience_level: 'Ten plus years',
    client_ip: '2600:8803:7b00:30c:5d67:66b7:1ef7:9acc',
    resume: {
      download_url:
        'https://api.lensa.com/coreg/v1/download-resume?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6IjMyOTliZjAwZjFiMzFmYTQ5NzY1MDQzYWNiZTFiZmE2LTIxODY0IiwibmFtZSI6Ikplbm5pZmVyIEZhcmhhIFJlc3VtZSAgNjIwMTkoZG9jeCkuZG9jIiwidHlwZSI6ImFwcGxpY2F0aW9uL3ZuZC5vcGVueG1sZm9ybWF0cy1vZmZpY2Vkb2N1bWVudC53b3JkcHJvY2Vzc2luZ21sLmRvY3VtZW50IiwidmFyaWFudCI6Im9yaWdpbmFsIiwiZXhwIjoxNTkzMzU5MzIxfQ.1kR0OULEZMsXiNEicWmougJaTnwEZ05mE0oSx6ZuOVI',
    },
    zip: '67202',
    desired_compensation: '$85,000',
    parsed_resume: {
      download_url:
        'https://api.lensa.com/coreg/v1/download-resume?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6IjMyOTliZjAwZjFiMzFmYTQ5NzY1MDQzYWNiZTFiZmE2LTIxODY0IiwibmFtZSI6Ikplbm5pZmVyIEZhcmhhIFJlc3VtZSAgNjIwMTkoZG9jeCkuZG9jLnhtbCIsInR5cGUiOiJ0ZXh0L3htbCIsInZhcmlhbnQiOiJwYXJzZWQiLCJleHAiOjE1OTMzNTkzMjF9.eA5XGSlmcpgR9oNAsew1-Rcyw9KpfdaSEItVDji7cVI',
    },
    last_name: 'Farha',
    email: 'jenfarha@gmail.com',
    city: 'Wichita',
    first_name: 'Jennifer',
    language: 'en',
    job_title: 'Regional Business Development Manager',
    candidate_source: 'lensa',
    target_id: '375e3fb986124c58bbff665dfe115444',
  },
  {
    state: 'VA',
    education_level: "Master's or Ph.D",
    experience_level: 'Ten plus years',
    client_ip: '72.83.101.156',
    resume: {
      download_url:
        'https://api.lensa.com/coreg/v1/download-resume?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6ImM3MTVkMzc0OWZjM2QyYmFiZjNkOTFhZDU1YTAxZDI3LTE1MDA2IiwibmFtZSI6IktBTC1TT0xVVElPTlMtQVJDSElURUNULVJFUzA0MzAyMC0xMS50eHQiLCJ0eXBlIjoidGV4dC9wbGFpbiIsInZhcmlhbnQiOiJvcmlnaW5hbCIsImV4cCI6MTU5MzM1OTMyMX0.fJzVTaSslYYJ3X-toSBISLMS1V_un2JXl94Tka7URf8',
    },
    zip: '20170',
    desired_compensation: '$30,000',
    parsed_resume: {
      download_url:
        'https://api.lensa.com/coreg/v1/download-resume?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6ImM3MTVkMzc0OWZjM2QyYmFiZjNkOTFhZDU1YTAxZDI3LTE1MDA2IiwibmFtZSI6IktBTC1TT0xVVElPTlMtQVJDSElURUNULVJFUzA0MzAyMC0xMS50eHQueG1sIiwidHlwZSI6InRleHQveG1sIiwidmFyaWFudCI6InBhcnNlZCIsImV4cCI6MTU5MzM1OTMyMX0.K8O01t-IE0c6ai2gH3RNTzNJpyQATkBYxiAeqSCUT-c',
    },
    last_name: 'Moharar',
    email: 'kmoharar@yahoo.com',
    city: 'Herndon',
    first_name: 'Kalyan',
    language: 'en',
    job_title: 'Senior Software Developer',
    candidate_source: 'lensa',
    target_id: '375e3fb986124c58bbff665dfe115444',
  },
  {
    state: 'OH',
    education_level: "Bachelor's Degree",
    experience_level: '6-10 years',
    client_ip: '98.31.17.70',
    resume: {
      download_url:
        'https://api.lensa.com/coreg/v1/download-resume?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6IjY0MDVkNGU0NDhmODFkMGUwYzU1ZjBkMWYwMzliYmI3LTMwOTkzIiwibmFtZSI6IktlbnRvbiBTY2h1bHplIFJlc3VtZSAoS2VudG9uIFNjaHVsemUpbWFuYWdlcihkb2N4KS5kb2MiLCJ0eXBlIjoiYXBwbGljYXRpb24vdm5kLm9wZW54bWxmb3JtYXRzLW9mZmljZWRvY3VtZW50LndvcmRwcm9jZXNzaW5nbWwuZG9jdW1lbnQiLCJ2YXJpYW50Ijoib3JpZ2luYWwiLCJleHAiOjE1OTMzNTkzMjF9.dfPX-FrwaJL2mfzuQ3vN9tt8fyUJxt3RkZ5oUHOFauw',
    },
    zip: '43215',
    desired_compensation: '$100,000',
    parsed_resume: {
      download_url:
        'https://api.lensa.com/coreg/v1/download-resume?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6IjY0MDVkNGU0NDhmODFkMGUwYzU1ZjBkMWYwMzliYmI3LTMwOTkzIiwibmFtZSI6IktlbnRvbiBTY2h1bHplIFJlc3VtZSAoS2VudG9uIFNjaHVsemUpbWFuYWdlcihkb2N4KS5kb2MueG1sIiwidHlwZSI6InRleHQveG1sIiwidmFyaWFudCI6InBhcnNlZCIsImV4cCI6MTU5MzM1OTMyMX0.KspcfSsBQGUT1_SZvtu736KPShfzCpaWEdKgyewvm2M',
    },
    last_name: 'Schulze',
    email: 'kentonschulze@hotmail.com',
    city: 'Columbus',
    first_name: 'Kenton',
    language: 'en',
    job_title: 'Sales Manager',
    candidate_source: 'lensa',
    target_id: '375e3fb986124c58bbff665dfe115444',
  },
  {
    state: 'TX',
    education_level: "Bachelor's Degree",
    experience_level: '6-10 years',
    client_ip: '2605:6000:1520:4781:98c8:482d:bfd3:7a93',
    resume: {
      download_url:
        'https://api.lensa.com/coreg/v1/download-resume?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6Ijc2OTQxMzZiMTM2MjE0ODcyZDJjMmFlOWUxYjg5ZDVmLTI5MTcyIiwibmFtZSI6IlNHcmFoYW1DVk5SZXN1bWUoZG9jeCkuZG9jIiwidHlwZSI6ImFwcGxpY2F0aW9uL3ZuZC5vcGVueG1sZm9ybWF0cy1vZmZpY2Vkb2N1bWVudC53b3JkcHJvY2Vzc2luZ21sLmRvY3VtZW50IiwidmFyaWFudCI6Im9yaWdpbmFsIiwiZXhwIjoxNTkzMzU5MzIxfQ.9QHnB5tByHqKYIuXoDP58tNq63P_vN8s7uvOjVZNMjk',
    },
    zip: '75060',
    desired_compensation: '$55,000',
    parsed_resume: {
      download_url:
        'https://api.lensa.com/coreg/v1/download-resume?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6Ijc2OTQxMzZiMTM2MjE0ODcyZDJjMmFlOWUxYjg5ZDVmLTI5MTcyIiwibmFtZSI6IlNHcmFoYW1DVk5SZXN1bWUoZG9jeCkuZG9jLnhtbCIsInR5cGUiOiJ0ZXh0L3htbCIsInZhcmlhbnQiOiJwYXJzZWQiLCJleHAiOjE1OTMzNTkzMjF9.8n0JEGo-0IMN33sv-PALFDXQO_c3n_wmkmSNPmB7jVM',
    },
    last_name: 'Graham',
    email: 'samanthatjones@icloud.com',
    city: 'Irving',
    first_name: 'Samantha',
    language: 'en',
    job_title: 'Hr Coordinator',
    candidate_source: 'lensa',
    target_id: '375e3fb986124c58bbff665dfe115444',
  },
  {
    state: 'AZ',
    education_level: 'High School Diploma',
    experience_level: '3-5 years',
    client_ip: '2600:1011:b15d:57c3:7888:6446:46ec:8560',
    resume: {
      download_url:
        'https://api.lensa.com/coreg/v1/download-resume?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6IjE5MzYzNzgzMGQ2YzEzN2ZkMmM3Njg4ZGE3ZDgwMmQwLTg2MTE0IiwibmFtZSI6IlNreWxhciBSeWFuIFJlc3VtZSAucGRmIiwidHlwZSI6ImFwcGxpY2F0aW9uL3BkZiIsInZhcmlhbnQiOiJvcmlnaW5hbCIsImV4cCI6MTU5MzM1OTMyMX0.TrNfeSCw469CCqCi7aCaYlB-KenchLVJPGzelwh8EOM',
    },
    zip: '85003',
    desired_compensation: '$40,000',
    parsed_resume: {
      download_url:
        'https://api.lensa.com/coreg/v1/download-resume?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6IjE5MzYzNzgzMGQ2YzEzN2ZkMmM3Njg4ZGE3ZDgwMmQwLTg2MTE0IiwibmFtZSI6IlNreWxhciBSeWFuIFJlc3VtZSAucGRmLnhtbCIsInR5cGUiOiJ0ZXh0L3htbCIsInZhcmlhbnQiOiJwYXJzZWQiLCJleHAiOjE1OTMzNTkzMjF9.DIJnng6xdvwf-ZRI5qbSFuoDUI_nIRscE5dSCq_G0K0',
    },
    last_name: 'Ryan',
    email: 'skylar.m.ryan@gmail.com',
    city: 'Phoenix',
    first_name: 'Skylar',
    language: 'en',
    job_title: 'Hr Coordinator',
    candidate_source: 'lensa',
    target_id: '375e3fb986124c58bbff665dfe115444',
  },
  {
    state: 'FL',
    education_level: "Bachelor's Degree",
    experience_level: 'Ten plus years',
    client_ip: '2603:9000:9d02:8ec4:d4c3:3a0d:21c2:3a3d',
    resume: {
      download_url:
        'https://api.lensa.com/coreg/v1/download-resume?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6IjI0MjU1NmI0MzJkYzBkYjUzOTRkYWEwNmExYzU0YzMxLTMxOTk0IiwibmFtZSI6ImptdWxob2xsYW5kIE1heTIwMjAgcmVzdW1lKGRvY3gpLmRvYyIsInR5cGUiOiJhcHBsaWNhdGlvbi92bmQub3BlbnhtbGZvcm1hdHMtb2ZmaWNlZG9jdW1lbnQud29yZHByb2Nlc3NpbmdtbC5kb2N1bWVudCIsInZhcmlhbnQiOiJvcmlnaW5hbCIsImV4cCI6MTU5MzM1OTMyMX0.s4CYa5gzYEBoKKVikMC4roob8fWqR7bwY46lvbEsJzY',
    },
    zip: '33602',
    desired_compensation: '$50,000',
    parsed_resume: {
      download_url:
        'https://api.lensa.com/coreg/v1/download-resume?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6IjI0MjU1NmI0MzJkYzBkYjUzOTRkYWEwNmExYzU0YzMxLTMxOTk0IiwibmFtZSI6ImptdWxob2xsYW5kIE1heTIwMjAgcmVzdW1lKGRvY3gpLmRvYy54bWwiLCJ0eXBlIjoidGV4dC94bWwiLCJ2YXJpYW50IjoicGFyc2VkIiwiZXhwIjoxNTkzMzU5MzIxfQ.FVhjewmyJei8lQeaCTYwdQ9NWls9kidXEVM3p_qIDeE',
    },
    last_name: 'Mulholland',
    email: 'jmulholland1809@gmail.com',
    city: 'Tampa',
    first_name: 'James',
    language: 'en',
    job_title: 'Sales Account Manager',
    candidate_source: 'lensa',
    target_id: '375e3fb986124c58bbff665dfe115444',
  },
  {
    state: 'TX',
    education_level: 'Some College',
    experience_level: 'Ten plus years',
    client_ip: '2605:6001:e8c5:4000:e1ea:56c7:ab28:f901',
    resume: {
      download_url:
        'https://api.lensa.com/coreg/v1/download-resume?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6IjE1ZTRjYjUyOGZiOGNjZDBiYmZkMWNkYTEzMjIzMTliLTU3NzUyIiwibmFtZSI6ImRldHJhcyByZXN1bWUgMDYtMTAtMjAyMC5vZHQiLCJ0eXBlIjoiYXBwbGljYXRpb24vdm5kLm9hc2lzLm9wZW5kb2N1bWVudC50ZXh0IiwidmFyaWFudCI6Im9yaWdpbmFsIiwiZXhwIjoxNTkzMzU5MzIxfQ.IHpGHKoHcPcrzTd04U-PcfTIrJ5nZx3JTdm-zXc0J1o',
    },
    zip: '75201',
    desired_compensation: '$40,000',
    parsed_resume: {
      download_url:
        'https://api.lensa.com/coreg/v1/download-resume?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6IjE1ZTRjYjUyOGZiOGNjZDBiYmZkMWNkYTEzMjIzMTliLTU3NzUyIiwibmFtZSI6ImRldHJhcyByZXN1bWUgMDYtMTAtMjAyMC5vZHQueG1sIiwidHlwZSI6InRleHQveG1sIiwidmFyaWFudCI6InBhcnNlZCIsImV4cCI6MTU5MzM1OTMyMX0.DYd4i6v4RHk3KR4AsZ2IddByeUP0qXVbNqKnm4uJXuA',
    },
    last_name: 'Dixon',
    email: 'dixon.detra@yahoo.com',
    city: 'Dallas',
    first_name: 'Detra',
    language: 'en',
    job_title: 'Leasing Consultant',
    candidate_source: 'lensa',
    target_id: '375e3fb986124c58bbff665dfe115444',
  },
  {
    state: 'DC',
    education_level: "Bachelor's Degree",
    experience_level: 'Less than 1 year',
    client_ip: '72.73.29.173',
    resume: {
      download_url:
        'https://api.lensa.com/coreg/v1/download-resume?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6IjE1ZWFjZjQxZWZlMGJhMjk2Mjk5YjIzOTJmM2Y5OTZlLTE3ODY5NyIsIm5hbWUiOiJOaWNvbGUgSGF3bGV5IFJlc3VtZS5wZGYiLCJ0eXBlIjoiYXBwbGljYXRpb24vcGRmIiwidmFyaWFudCI6Im9yaWdpbmFsIiwiZXhwIjoxNTkzMzU5MzIxfQ.lfPL6UVV1O-PqEuR0-FZLpnRY_c7VGTzjDagC2IQ-BI',
    },
    zip: '20004',
    desired_compensation: '$40,000',
    parsed_resume: {
      download_url:
        'https://api.lensa.com/coreg/v1/download-resume?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6IjE1ZWFjZjQxZWZlMGJhMjk2Mjk5YjIzOTJmM2Y5OTZlLTE3ODY5NyIsIm5hbWUiOiJOaWNvbGUgSGF3bGV5IFJlc3VtZS5wZGYueG1sIiwidHlwZSI6InRleHQveG1sIiwidmFyaWFudCI6InBhcnNlZCIsImV4cCI6MTU5MzM1OTMyMX0.5YN-U6uYjaIO8_OS9qh6B1_O7Hhhr_xkn71T9YD3AlA',
    },
    last_name: 'Hawley',
    email: 'nicoleehawley@yahoo.com',
    city: 'Washington',
    first_name: 'Nicole',
    language: 'en',
    job_title: 'Hr Assistant',
    candidate_source: 'lensa',
    target_id: '375e3fb986124c58bbff665dfe115444',
  },
  {
    state: 'IL',
    education_level: "Bachelor's Degree",
    experience_level: 'Ten plus years',
    client_ip: '2601:240:4a00:a6e0:3154:c0b9:3bea:9c42',
    resume: {
      download_url:
        'https://api.lensa.com/coreg/v1/download-resume?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6ImI3MDhiNjkxYmY1OGU0Y2RkNjk5ZGM5YjFlYzQ3ZDExLTI1ODk2IiwibmFtZSI6IkJyaWFuIFppbW1lcm1hbiBSZXN1bWUgVjEoZG9jeCkuZG9jIiwidHlwZSI6ImFwcGxpY2F0aW9uL3ZuZC5vcGVueG1sZm9ybWF0cy1vZmZpY2Vkb2N1bWVudC53b3JkcHJvY2Vzc2luZ21sLmRvY3VtZW50IiwidmFyaWFudCI6Im9yaWdpbmFsIiwiZXhwIjoxNTkzMzU5MzIxfQ.dLDi6Cy23-8X6eYt8IMPvW79JeYtZRgfrb7lOaspO5Y',
    },
    zip: '60602',
    desired_compensation: '$150,000',
    parsed_resume: {
      download_url:
        'https://api.lensa.com/coreg/v1/download-resume?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6ImI3MDhiNjkxYmY1OGU0Y2RkNjk5ZGM5YjFlYzQ3ZDExLTI1ODk2IiwibmFtZSI6IkJyaWFuIFppbW1lcm1hbiBSZXN1bWUgVjEoZG9jeCkuZG9jLnhtbCIsInR5cGUiOiJ0ZXh0L3htbCIsInZhcmlhbnQiOiJwYXJzZWQiLCJleHAiOjE1OTMzNTkzMjF9.lcifZQTF8WMXlayz2edcanqn5YoPhXhdj9Y7KYjAzTs',
    },
    last_name: 'Zimmerman',
    email: 'zimmer_b@yahoo.com',
    city: 'Chicago',
    first_name: 'Brian',
    language: 'en',
    job_title: 'Sales Territory Manager',
    candidate_source: 'lensa',
    target_id: '375e3fb986124c58bbff665dfe115444',
  },
  {
    state: 'MA',
    client_ip: '216.49.151.32',
    resume: {
      download_url:
        'https://api.lensa.com/coreg/v1/download-resume?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6ImE0ZGZlNjAxYWFiZDUzM2FhZTFmOWM2MmI4ODNkNDdiLTE3NDQzNiIsIm5hbWUiOiJGbGFuaWdhbiwgSnVkeSAtIFJlc3VtZS5wZGYiLCJ0eXBlIjoiYXBwbGljYXRpb24vcGRmIiwidmFyaWFudCI6Im9yaWdpbmFsIiwiZXhwIjoxNTkzMzU5MzIxfQ.w0VX--J6vBwEQFwsmAlNkq8h2mpZO_yfpv4jf2cT4dE',
    },
    zip: '01752',
    parsed_resume: {
      download_url:
        'https://api.lensa.com/coreg/v1/download-resume?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6ImE0ZGZlNjAxYWFiZDUzM2FhZTFmOWM2MmI4ODNkNDdiLTE3NDQzNiIsIm5hbWUiOiJGbGFuaWdhbiwgSnVkeSAtIFJlc3VtZS5wZGYueG1sIiwidHlwZSI6InRleHQveG1sIiwidmFyaWFudCI6InBhcnNlZCIsImV4cCI6MTU5MzM1OTMyMX0.fmqg4oF0-kSrWYVHpYwLCrsvwle8vZHz6qpJEGlaR7U',
    },
    last_name: 'Flanigan',
    email: 'judyflanigan0826@gmail.com',
    city: 'Marlborough',
    first_name: 'Judy',
    language: 'en',
    job_title: 'Hr',
    candidate_source: 'lensa',
    target_id: '375e3fb986124c58bbff665dfe115444',
  },
  {
    state: 'CT',
    education_level: "Master's or Ph.D",
    experience_level: 'Ten plus years',
    client_ip: '2601:186:4301:ccf0:88d1:ee81:812a:cd13',
    resume: {
      download_url:
        'https://api.lensa.com/coreg/v1/download-resume?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6IjQwZTc3YzFmNThmMTNiNzhiOTE2ZDgwZDc1YTA4ZTZiLTIyMzA1IiwibmFtZSI6IlJlc3VtZSBIYXJ0IEpHIEZlYiAyMDIwKGRvY3gpLmRvYyIsInR5cGUiOiJhcHBsaWNhdGlvbi92bmQub3BlbnhtbGZvcm1hdHMtb2ZmaWNlZG9jdW1lbnQud29yZHByb2Nlc3NpbmdtbC5kb2N1bWVudCIsInZhcmlhbnQiOiJvcmlnaW5hbCIsImV4cCI6MTU5MzM1OTMyMX0.p-rfm7_5fNSc31l7TpqhD9X9A8uaUojAma_OK5ABotM',
    },
    zip: '06051',
    desired_compensation: '$165,000',
    parsed_resume: {
      download_url:
        'https://api.lensa.com/coreg/v1/download-resume?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6IjQwZTc3YzFmNThmMTNiNzhiOTE2ZDgwZDc1YTA4ZTZiLTIyMzA1IiwibmFtZSI6IlJlc3VtZSBIYXJ0IEpHIEZlYiAyMDIwKGRvY3gpLmRvYy54bWwiLCJ0eXBlIjoidGV4dC94bWwiLCJ2YXJpYW50IjoicGFyc2VkIiwiZXhwIjoxNTkzMzU5MzIxfQ.SSEBnbpRDjG6MbPh8cjPHgOcKVChiIVOg1F1N2zgB10',
    },
    last_name: 'Hart',
    email: 'jghart45@gmail.com',
    city: 'New Britain',
    first_name: 'John',
    language: 'en',
    job_title: 'Regional Manager',
    candidate_source: 'lensa',
    target_id: '375e3fb986124c58bbff665dfe115444',
  },
]
